# -*- coding: utf-8 -*-
"""Post del blog — ITALIANO. 7 articoli, allineati alla SEO del settore interior design."""

BLOG = [
    {
        "slug": "whats-new-in-interiors",
        "date": "2026-08-01",
        "category": "Tendenze",
        "read_time": 6,
        "image": "blog-4.jpg",
        "title": "Cosa c’è di nuovo negli interni, in questo momento",
        "excerpt": "Neutri caldi, luce scultorea e mobili che si guadagnano il proprio posto: una breve guida alla direzione che gli interni stanno prendendo in questa stagione.",
        "meta": "Tendenze interior design da osservare: neutri caldi, illuminazione scultorea, mobili a scala umana e il ritorno dell’artigianato. Appunti di Bruno Vinícius.",
        "blocks": [
            {"t": "p", "c": "Le tendenze sono utili solo se ti aiutano a prendere una decisione. Tutto ciò che segue è una direzione, non una regola — prendi ciò che sostiene il modo in cui vivi davvero e lascia perdere il resto."},
            {"t": "h2", "c": "I neutri caldi sono tornati, e non sono beige"},
            {"t": "p", "c": "I grigi freddi che hanno dominato gli interni per un decennio stanno lasciando il posto a neutri più caldi e profondi — pensa alla pietra, alla sabbia, al fungo, all’oliva. La differenza conta: i neutri caldi trattengono più luce e fotografano meglio, e fanno stare bene le persone in una stanza."},
            {"t": "p", "c": "Il modo di usarli senza appiattire lo spazio è il contrasto di texture, non di colore. Una parete color sabbia diventa ricca quando incontra un divano in lino, un tavolo in travertino e un pavimento in noce scuro."},
            {"t": "h2", "c": "L’illuminazione è diventata la protagonista"},
            {"t": "p", "c": "Le lampade a sospensione non sono più un accessorio. Vetro scultoreo e lampade soffiate a mano stanno assumendo il ruolo che un tempo spettava al lampadario: la prima cosa che si nota entrando in una stanza. Il principio è lo stesso che le grandi maison dell’illuminazione praticano da decenni: la luce come materiale primario, e tutto il resto disposto intorno ad essa."},
            {"t": "quote", "c": "La luce è il primo materiale che scelgo. Tutto il resto — colore, arredo, disposizione — viene negoziato intorno ad essa."},
            {"t": "h2", "c": "Mobili che si guadagnano il proprio posto"},
            {"t": "p", "c": "L’altro segnale chiaro è l’allontanamento dagli abbinamenti. I completi coordinati stanno scomparendo a favore di pezzi singoli, ben scelti, che possono seguirti nella vita: una poltrona scultorea, un tavolo da ereditare, una lampada che conserverai per vent’anni."},
            {"t": "h2", "c": "Come seguire le novità senza perdere te stesso"},
            {"t": "p", "c": "Ci sono due luoghi utili dove osservare i nuovi prodotti prima che arrivino nei negozi. Il primo sono i laboratori e le officine indipendenti, che tendono a produrre piccole serie di oggetti onesti. Il secondo sono le piattaforme di crowdfunding, dove i designer indipendenti lanciano mobili, lampade e accessori direttamente — spesso con una stagione di anticipo rispetto alla distribuzione, e di solito ancora con la storia del progetto attaccata."},
            {"t": "p", "c": "Nessuno dei due sostituisce la visita in showroom. Ma entrambi sono ottimi per intercettare quelle piccole idee specifiche — un nuovo piede di tavolo, un nuovo modo di piegare la luce, che rendono una stanza attuale senza sembrare un catalogo."},
            {"t": "h2", "c": "In sintesi"},
            {"t": "ul", "c": [
                "Scegli neutri caldi e profondi e aggiungi ricchezza con la texture, non con il colore.",
                "Affida a un solo apparecchio il ruolo di protagonista — investi lì il budget.",
                "Compra pezzi singoli con una storia, non completi coordinati.",
                "Segui artigiani e lanci indipendenti per le idee che arrivano in anticipo.",
            ]},
            {"t": "p", "c": "Le tendenze vanno e vengono. Se disegni una stanza che sostiene le tue abitudini e ti fa sentire a tuo agio, sarà giusta questa stagione e lo sarà anche tra dieci."},
        ],
    },
    {
        "slug": "how-to-choose-an-interior-design-style",
        "date": "2026-07-14",
        "category": "Basi",
        "read_time": 6,
        "image": "blog-5.jpg",
        "title": "Come scegliere uno stile d’arredo che si adatti alla tua vita",
        "excerpt": "I quiz sullo stile sbagliano il punto. La direzione giusta nasce da come vivi, non da Pinterest. Un metodo pratico per trovare il tuo.",
        "meta": "Come scegliere uno stile d’arredo: un processo pratico basato su come vivi, lavori e ricevi. invece di Pinterest o dei quiz sullo stile.",
        "blocks": [
            {"t": "p", "c": "I clienti arrivano spesso con una dozzina di immagini salvate e una frase presa in prestito da una rivista: “scandinavo”, “organico moderno”, “quiet luxury”. Nessuna di queste è sbagliata. Sono solo punti di partenza, e la maggior parte descrive lo stesso impulso di fondo: uno spazio che sembri calmo e onesto."},
            {"t": "h2", "c": "Inizia dai comportamenti, non dal vocabolario"},
            {"t": "p", "c": "Prima di pensare a materiali o colori, rispondi con onestà a tre domande. Come usi davvero la stanza, ora per ora? Chi la condivide con te, e con quale frequenza? E come vuoi sentirti quando entri — riposato, carico di energia, accolto, concentrato? Lo stile è la risposta a queste domande, espressa in forma fisica. Tutto il resto è decorazione."},
            {"t": "h2", "c": "Separa ciò che ami da ciò con cui vuoi vivere"},
            {"t": "p", "c": "È questa la distinzione che conta. Una hall d’albergo può essere magnifica e rimanere comunque il modello sbagliato per il tuo salotto, perché un albergo è pensato per una sosta di trenta minuti. La tua casa è pensata per un decennio di serate ordinarie. Raccogli le immagini che ami, poi dividile in due elenchi: ispiranti e realmente vivibili. La sovrapposizione è il tuo stile."},
            {"t": "quote", "c": "Uno stile che ti chiede di cambiare il modo in cui vivi non sopravviverà al contatto con la tua vita."},
            {"t": "h2", "c": "Lavora con un unico riferimento forte"},
            {"t": "p", "c": "Dalla sovrapposizione, scegli una sola direzione come ancora — la palette o il pezzo chiave di cui sei certo, e lascia che tutto il resto venga negoziato intorno ad essa. Le stanze che sembrano indecise di solito hanno due o tre riferimenti forti che tirano in direzioni opposte. Un’ancora sola, applicata con coerenza, è ciò che rende una stanza progettata anziché decorata."},
            {"t": "h2", "c": "Una rapida checklist"},
            {"t": "ul", "c": [
                "Annota come viene usata la stanza nel corso di una settimana normale.",
                "Tieni una cartella di immagini; dividila tra ‘ispiranti’ e ‘vivibili’.",
                "Scegli un’ancora sola — una palette, un materiale o un unico pezzo.",
                "Metti alla prova l’ancora contro le tue abitudini quotidiane, non contro una fotografia.",
                "Concediti di rubare un solo dettaglio che semplicemente ti piace.",
            ]},
            {"t": "p", "c": "Nei momenti di dubbio, preferisci la semplicità alla tendenza. È più facile aggiungere personalità a una base calma che sottrarla a una base movimentata — ed è su quella base calma che alla fine la maggior parte delle persone vuole vivere."},
        ],
    },
    {
        "slug": "the-quiet-power-of-lighting",
        "date": "2026-06-28",
        "category": "Illuminazione",
        "read_time": 7,
        "image": "blog-3.jpg",
        "title": "Il potere silenzioso dell’illuminazione: una guida per chi progetta",
        "excerpt": "L’illuminazione decide come si sente una stanza, non come appare. Tre livelli di luce, cinque errori e come fare bene in casa tua.",
        "meta": "Guida all’illuminazione d’interni: i tre livelli di luce, gli errori più comuni e come progettare una luce che cambia l’atmosfera di una stanza.",
        "blocks": [
            {"t": "p", "c": "La gente ricorda i mobili e dimentica la luce. Eppure è la luce a rendere una stanza generosa alle sette di sera e calma alle undici. La maggior parte degli interni è pensata per come appare in fotografia; quelli che si sentono giusti sono progettati intorno a come si comportano nelle diverse ore del giorno."},
            {"t": "h2", "c": "I tre livelli di luce"},
            {"t": "p", "c": "Una buona illuminazione raramente è un unico apparecchio. Sono tre livelli che lavorano insieme, ognuno con un compito diverso:"},
            {"t": "ul", "c": [
                "Luce ambientale: una luce morbida e uniforme che riempie la stanza senza abbagliare. Incassata o indiretta, regolabile, intorno ai 2.700K.",
                "Luce da compito: una luce focalizzata dove leggi, cucini o lavori. Una buona lampada da lettura o una striscia sotto il pensile fanno più di quanto immagini.",
                "Luce d’accento — la luce che cattura lo sguardo: una light da quadro, un wall-washer, un apparecchio che illumina di bagliore anziché di piena luce.",
            ]},
            {"t": "h2", "c": "L’interruttore che userai davvero"},
            {"t": "p", "c": "L’intervento più efficace in assoluto in qualunque stanza è un dimmer sul circuito dell’ambiente. Costa poco e raddoppia silenziosamente il numero di atmosfere che una stanza può contenere. Luminosa per la mattina e per i compiti, bassa per la sera, a metà per i ricevimenti. Le stanze con un solo livello di luce tendono a sembrare o cliniche o buie."},
            {"t": "quote", "c": "Una stanza è un posto diverso alle sei del mattino e alle dieci di sera. La sua luce deve poter cambiare idea."},
            {"t": "h2", "c": "Cinque errori che invecchiano una stanza"},
            {"t": "ul", "c": [
                "Un’unica luce centrale senza dimmer — il modo più rapido per far sembrare una stanza una sala d’attesa.",
                "Illuminazione che punta solo verso il basso. La luce di parete e di pavimento, rimbalzata sulle superfici, fa sembrare i soffitti più alti e i volti più gentili.",
                "Bianco freddo nelle zone abitative. Riserva i 4.000K e oltre agli spazi tecnici; tieni i soggiorni caldi.",
                "Nessuna luce all’altezza umana. Una lampada all’altezza degli occhi, da seduti, cambia tutto.",
                "Dimenticare le luci che si vedono da spente. Una stanza bella con un apparecchio di plastica economico è una contraddizione.",
            ]},
            {"t": "h2", "c": "Dove investire"},
            {"t": "p", "c": "Se il budget consente un solo acquisto generoso in una stanza, fallo sull’apparecchio che vedi entrando — la sospensione o la lampada da parete che porta il livello d’accento. È il pezzo che lavora di più e quello di cui la gente ti chiederà."},
        ],
    },
    {
        "slug": "small-spaces-big-impact",
        "date": "2026-06-02",
        "category": "Spazi",
        "read_time": 6,
        "image": "blog-1.jpg",
        "title": "Spazi piccoli, grande impatto: progettare case compatte",
        "excerpt": "Le stanze piccole falliscono per il disordine, non per le dimensioni. Cinque principi per rendere generoso uno spazio compatto senza spostare muri.",
        "meta": "Principi di design per spazi piccoli: luce, scala, contenimento e un unico pezzo forte per rendere generose le case compatte.",
        "blocks": [
            {"t": "p", "c": "Una stanza piccola raramente ha bisogno di essere più grande. Ha bisogno di meno cose, ma meglio scelte, e di un’idea più chiara di a cosa serve. Quasi ogni progetto compatto su cui lavoro migliora nel momento in cui togliamo qualcosa anziché aggiungerla."},
            {"t": "h2", "c": "Un solo compito per stanza, detto con onestà"},
            {"t": "p", "c": "Un open-space cucina-soggiorno che cerca di essere allo stesso tempo sala da pranzo, ufficio, cinema e sala giochi non sembrerà nessuno di questi. Dai a ogni zona un unico compito chiaro e lascia respirare lo spazio intorno. Se un angolo non ha uno scopo definito, lascialo libero — il vuoto è un lusso, soprattutto nelle case piccole."},
            {"t": "h2", "c": "Lascia che sia la luce a fare il lavoro spaziale"},
            {"t": "p", "c": "La luce è il modo più economico per far sembrare una stanza più grande. Tieni le finestre libere da tende pesanti, usa toni di parete chiari che riflettono la luce anziché assorbirla, e fai rimbalzare la luce su soffitto e pareti invece di illuminare da un solo punto. Una stanza piccola che riceve luce morbida e indiretta si percepisce più grande di una stanza grande in ombra."},
            {"t": "quote", "c": "In uno spazio piccolo, ogni decisione è uno scambio. Il segreto è scegliere a cosa rinunciare."},
            {"t": "h2", "c": "La scala è tutto"},
            {"t": "p", "c": "Un errore comune è comprare mobili troppo piccoli, sperando che la stanza sembri più grande. Ottiene l’effetto opposto. Un divano compatto dalle proporzioni giuste, un tappeto che ancora la zona e un unico pezzo generoso — una poltrona, un tavolo, una lampada, danno all’occhio una scala con cui leggere la stanza. Tutto piccolo si legge come piccolo."},
            {"t": "h2", "c": "Contenitori che scompaiono"},
            {"t": "p", "c": "Il rumore visivo di una casa piccola viene soprattutto dagli oggetti senza una casa. Arredi su misura, tinteggiati per fondersi con la parete, eliminano il disordine alla fonte. Dai a ogni categoria di oggetti un posto designato — scarpe, cappotti, carte, cavi, e la stanza stessa comincia a sembrare più grande."},
            {"t": "h2", "c": "I cinque principi"},
            {"t": "ul", "c": [
                "Dai a ogni zona un solo compito chiaro; lascia un angolo vuoto apposta.",
                "Massimizza la luce naturale e mantieni riflettenti i toni delle pareti.",
                "Compra mobili della scala giusta e investi in un unico pezzo forte.",
                "Nascondi il contenimento nell’architettura anziché aggiungere altri mobili.",
                "Seleziona con rigore: tutto ciò che è visibile deve guadagnarsi il suo posto.",
            ]},
        ],
    },
    {
        "slug": "color-as-a-tool",
        "date": "2026-05-12",
        "category": "Colore",
        "read_time": 6,
        "image": "blog-2.jpg",
        "title": "Il colore come strumento: costruire una palette che funziona",
        "excerpt": "Dimentica l’abbinamento divano-tappeto. Il colore funziona come sistema. luce, profondità e un’unica mossa forte. Ecco come costruire una palette che regge.",
        "meta": "Come costruire una palette di colori per interni: la regola 60-30-10, luce calda e fredda, saturazione e un unico tocco forte, spiegate in modo semplice.",
        "blocks": [
            {"t": "p", "c": "La maggior parte delle persone sceglie i colori come sceglie un abito che ama in una fotografia — e poi si chiede perché il risultato non tenga. In una stanza il colore funziona come un sistema, con una gerarchia, e il sistema conta più di qualsiasi singolo colore."},
            {"t": "h2", "c": "Inizia dalla luce della stanza, non dalla tendenza"},
            {"t": "p", "c": "La stessa tinta si legge diversamente sotto la luce nord, il sole del pomeriggio e le lampadine calde. Una stanza esposta a nord ha bisogno di toni caldi per sembrare viva; una stanza inondata di sole può sostenere toni più freddi. Prima di campionare i colori, osserva la luce: da che direzione arriva, come cambia nel corso della giornata e se le lampadine sono calde o fredde."},
            {"t": "h2", "c": "La struttura 60-30-10"},
            {"t": "ul", "c": [
                "60%: il tono dominante: pareti, pavimento e le superfici più grandi. Tienilo quieto.",
                "30%: il tono secondario: il divano, gli arredi fissi, i mobili principali. In dialogo con il primo.",
                "10%: l’accento: cuscini, una poltrona, un tappeto, l’arte. È qui che vive la personalità, e deve restare un azionista di minoranza.",
            ]},
            {"t": "quote", "c": "Una palette non è una raccolta di colori preferiti. È un insieme di colori che hanno accettato di lavorare insieme."},
            {"t": "h2", "c": "Una mossa forte batte cinque mosse carine"},
            {"t": "p", "c": "Le stanze che sembrano indecise di solito hanno più colori, ognuno impegnato in un piccolo compito. Le stanze che sembrano progettate hanno un’unica mossa forte — una parete profonda in una stanza piccola, un’isola da cucina satura, un tappeto colorato generoso, e lasciano che tutto il resto ricada in silenzio intorno. Decidi dove vuoi che l’occhio si posi, e metti lì il colore più audace e da nessun’altra parte."},
            {"t": "h2", "c": "Una prova pratica"},
            {"t": "p", "c": "Campiona sulla parete, nella stanza reale, e guardala in tre momenti della giornata. Boccette di prova economiche e una settimana di pazienza risparmiano il costo di una ritinteggiatura completa. E quando sarai arrivato a due palette, scegli quella che ti sembra più calma — il colore è più facile da aggiungere dopo e più difficile da togliere."},
        ],
    },
    {
        "slug": "what-the-design-process-looks-like",
        "date": "2026-04-20",
        "category": "Processo",
        "read_time": 5,
        "image": "blog-5.jpg",
        "title": "Com’è fatto il processo di design, passo dopo passo",
        "excerpt": "Dalla prima telefonata al risultato finale. una passeggiata onesta e in parole semplici attraverso il modo in cui si svolge davvero un progetto residenziale.",
        "meta": "Il processo di interior design passo dopo passo: scoperta, concept, sviluppo, consegna. Cosa aspettarsi dai clienti in ogni fase.",
        "blocks": [
            {"t": "p", "c": "I clienti mi dicono che la parte più spaventosa di un progetto è l’ignoto: quanto durerà, chi fa cosa e dove vanno i soldi. Ecco il processo che uso, in parole semplici, così sai cosa aspettarti."},
            {"t": "h2", "c": "1. Scoperta"},
            {"t": "p", "c": "Parliamo di come vivi, lavori e ricevi — le routine, le abitudini, le cose che ti danno fastidio oggi nello spazio. Ascolto per capire la sensazione che vuoi che la stanza porti. Questa fase non ti costa nulla oltre a un’ora, e mi dice se siamo una buona combinazione."},
            {"t": "h2", "c": "2. Progetto"},
            {"t": "p", "c": "Concept, atmosfera, materiali e disposizione — sviluppati insieme e rifiniti finché non sembrano inevitabili. Vedrai piante, palette e campioni di materiale, e andremo avanti e indietro finché il progetto non corrisponde al modo in cui vivi davvero. È qui che la visione prende forma, prima che un solo muro venga toccato."},
            {"t": "h2", "c": "3. Sviluppo"},
            {"t": "p", "c": "Disegni tecnici, approvvigionamenti e coordinamento con costruttori e artigiani, gestito dall’inizio alla fine. Ricevi budget chiari e una tempistica realistica, e mi occupo io dei fornitori così non sei tu l’intermediario. Le incognite vengono risolte qui, sulla carta, dove costano poco."},
            {"t": "quote", "c": "Un buon processo sposta i problemi sulla carta per tempo, dove sono economici da risolvere — non sul cantiere, dove sono costosi."},
            {"t": "h2", "c": "4. Consegna"},
            {"t": "p", "c": "Installazione e styling, fino all’ultimo oggetto. Lo spazio viene consegnato pronto per essere abitato — non allestito per una fotografia, ma disposto per la tua settimana. È il momento in cui tutto si incastra in silenzio, ed è il motivo per cui il processo esiste."},
            {"t": "h2", "c": "Cosa chiedere a qualsiasi progettista prima di iniziare"},
            {"t": "ul", "c": [
                "Come gestite il budget — e cosa succede se cambia?",
                "Chi gestisce fornitori, imprese e tempistiche?",
                "Cosa fate quando un prodotto scelto viene tolto dal mercato?",
                "Come comunicheremo, e con quale frequenza?",
                "Cosa copre il compenso e cosa ne è escluso?",
            ]},
            {"t": "p", "c": "Il processo giusto è quello che ti tiene informato senza sommergerti di dettagli. Dovresti sempre sapere in che fase è il progetto, cosa succede dopo e quanto costa."},
        ],
    },
    {
        "slug": "seven-common-interior-design-mistakes",
        "date": "2026-03-30",
        "category": "Basi",
        "read_time": 6,
        "image": "blog-6.jpg",
        "title": "Sette errori comuni di interior design (e come evitarli)",
        "excerpt": "Gli errori che invecchiano in silenzio una stanza non riguardano il gusto. riguardano la sequenza e la scala. Una checklist pratica prima di ristrutturare.",
        "meta": "Errori comuni di interior design da evitare: illuminazione, scala, colore, contenimento e sequenza. Una checklist pratica per la ristrutturazione.",
        "blocks": [
            {"t": "p", "c": "Dopo abbastanza progetti cominci a vedere sempre gli stessi sette errori ripetersi — non in case brutte, ma in case curate e piene di buone intenzioni. Nessuno di questi riguarda il gusto. Riguardano la sequenza, la scala e dove finisce l’attenzione."},
            {"t": "h2", "c": "1. Progettare l’arredo prima della disposizione"},
            {"t": "p", "c": "Scegliere un divano prima di decidere come scorre la stanza è come comprare vestiti prima di sapere dove andrai. Inizia da come viene usato lo spazio e da come le persone lo attraversano; i pezzi vengono dopo."},
            {"t": "h2", "c": "2. Comprare tutto da un unico showroom"},
            {"t": "p", "c": "Un completo coordinato è comodo e dimenticabile. Le stanze con personalità nascono da pezzi con storie diverse — una poltrona vintage accanto a un divano contemporaneo, un tavolo fatto a mano sotto una lampada di serie. Se tutto combacia, niente conta."},
            {"t": "h2", "c": "3. Appendere le opere troppo in alto"},
            {"t": "p", "c": "Il centro di un quadro dovrebbe stare all’altezza degli occhi quando sei in piedi — circa 145–150 cm dal pavimento. Sopra i divani, il bordo inferiore dovrebbe superare lo schienale di circa 15–20 cm. L’arte fluttua quando è appesa come una targhetta da museo."},
            {"t": "h2", "c": "4. Combattere la luce invece di usarla"},
            {"t": "p", "c": "Scegliere pareti scure e cupe per una stanza esposta a nord, o un’unica luce centrale senza dimmer, sono entrambi modi di perdere la battaglia con la condizione naturale della stanza. Progetta con la luce che hai prima di aggiungerne altra."},
            {"t": "h2", "c": "5. Ridurre tutto in scala"},
            {"t": "p", "c": "I mobili troppo piccoli fanno sembrare una stanza più piccola e più vuota. Compra alla scala giusta per lo spazio e lascia che un solo pezzo sia generoso."},
            {"t": "h2", "c": "6. Arredare la pianta, non la stanza"},
            {"t": "p", "c": "Le piante mentono. Il vero carattere di una stanza viene da come si sente in tre dimensioni — la profondità di un corridoio, l’altezza di un soffitto, il percorso della luce solare sul pavimento. Dedica tanto tempo a immaginarti nella stanza quanto a disporla sulla carta."},
            {"t": "h2", "c": "7. Aggiungere prima di togliere"},
            {"t": "p", "c": "Quando una stanza non sembra giusta, l’istinto è di aggiungere un altro oggetto. Di solito è l’istinto sbagliato. Togli prima — uno strato di oggetti, un tappeto affollato, una lampada duplicata, e guarda cosa la stanza stava cercando di essere. La maggior parte delle stanze migliora più per sottrazione che per addizione."},
            {"t": "quote", "c": "Il modo più rapido per far sembrare migliore una stanza è toglierci qualcosa."},
        ],
    },
]
