# -*- coding: utf-8 -*-
"""Site content — Bruno Vinícius Interior Design. All copy in 5 languages."""

LANGUAGES = {
    "en": {
        "native": "English",
        "short": "EN",
        "html": "en",
        "prefix": "",
        "root": "/",
        "text_dir": "ltr",
    },
    "es": {
        "native": "Español",
        "short": "ES",
        "html": "es",
        "prefix": "/es",
        "root": "/es/",
        "text_dir": "ltr",
    },
    "it": {
        "native": "Italiano",
        "short": "IT",
        "html": "it",
        "prefix": "/it",
        "root": "/it/",
        "text_dir": "ltr",
    },
    "fr": {
        "native": "Français",
        "short": "FR",
        "html": "fr",
        "prefix": "/fr",
        "root": "/fr/",
        "text_dir": "ltr",
    },
    "pt": {
        "native": "Português",
        "short": "PT",
        "html": "pt",
        "prefix": "/pt",
        "root": "/pt/",
        "text_dir": "ltr",
    },
}

DEFAULT_LANG = "en"

SITE = {
    "en": {
        "brand": "Bruno Vinícius",
        "studio": "Interior Design",
        "nav": {
            "work": "Work",
            "about": "About",
            "services": "Services",
            "journal": "Journal",
            "contact": "Contact",
            "cta": "Start a project",
            "view_project": "View project",
            "prev_project": "Previous project",
            "next_project": "Next project",
            "other_langs": "Read in",
            "back_to_work": "Back to work",
        },
        "meta": {
            "title": "Bruno Vinícius — Interior Design Studio",
            "description": "Bespoke interior design for residential and hospitality spaces worldwide. Calm, layered interiors, made to be lived in.",
        },
        "hero": {
            "eyebrow": "Interior design studio",
            "h1_before": "Interiors with",
            "h1_em": "intention.",
            "sub": "I design residential and hospitality spaces for clients around the world. calm, layered, and made to be lived in.",
            "cta_primary": "Start a project",
            "cta_secondary": "Selected work",
            "scroll": "Scroll",
        },
        "statement": {
            "text": "Good rooms don’t shout. They hold a quiet presence — shaped by light, proportion, and the small details you feel more than you notice. That is the kind of space I design: one that feels like you, only more considered.",
        },
        "work": {
            "title": "Selected Work",
            "sub": "A small selection of residential and hospitality projects. from full-scale renovations to tailored e-design.",
            "view_all": "View all projects",
            "filter_all": "All",
        },
        "about": {
            "title": "About",
            "heading": "Design is a way of listening.",
            "p1": "I’m Bruno Vinícius, an interior designer working on residential and hospitality projects across Europe and the Americas.",
            "p2": "My work sits between contemporary restraint and warm, familiar detail. The best interiors start with how a space should feel, not how it should look — light, proportion, and honest materials do most of the work.",
            "p3": "Trained in architecture and design, I run a boutique online studio, meeting clients wherever they are and delivering projects that travel well.",
            "process_title": "How we work",
            "process": [
                {"t": "Discover", "d": "We talk through how you live, work, and host. I listen for the feeling you want the space to carry."},
                {"t": "Design", "d": "Concept, mood, materials, and layout — developed together, refined until it feels inevitable."},
                {"t": "Develop", "d": "I handle technical drawings, sourcing, and coordination with builders and artisans, from start to finish."},
                {"t": "Deliver", "d": "Installation and styling, down to the last object. The space is handed over ready to live in."},
            ],
            "note": "Clear budgets, honest timelines, no surprises.",
        },
        "services": {
            "title": "Services",
            "sub": "Six ways of working together. from a single room to a full project, in person or remotely.",
            "items": [
                {"t": "Residential Design", "d": "Complete design for homes and apartments — layout, materials, and styling, from first sketch to final reveal."},
                {"t": "Hospitality & Commercial", "d": "Restaurants, boutiques, and workspaces designed to welcome people and perform all day."},
                {"t": "Kitchen & Bath", "d": "Precise, personal, and practical — the most-used rooms, done right."},
                {"t": "Lighting Design", "d": "Layered lighting plans that shift a room’s mood from morning to evening."},
                {"t": "E-Design / Online", "d": "Full design packages delivered remotely, with shopping lists and guidance you can execute anywhere."},
                {"t": "Design Consultation", "d": "A focused session to solve a specific room, project, or problem."},
            ],
        },
        "testimonials": {
            "title": "Kind words",
            "items": [
                {"q": "Bruno listened before he sketched. The result is a home that finally feels like us.", "a": "Renata M.", "r": "Residential client"},
                {"q": "From concept to installation everything was calm, precise, and on time. The lighting alone changed everything.", "a": "Thomas L.", "r": "Hospitality client"},
                {"q": "We redesigned remotely from another continent. The process was clear and the outcome exceeded our expectations.", "a": "Sara & Mark", "r": "E-design clients"},
            ],
        },
        "journal": {
            "title": "Journal",
            "sub": "Notes on light, colour, and the craft of making rooms feel right.",
            "read": "Read",
            "all": "All articles",
        },
        "contact": {
            "title": "Start a project",
            "sub": "Tell me about your space and how you want to live in it. I respond within two business days.",
            "name": "Name",
            "email": "Email",
            "type": "Project type",
            "type_placeholder": "Residential, hospitality, e-design…",
            "message": "Tell me about your project",
            "submit": "Send message",
            "sending": "Sending…",
            "success": "Thank you — your message is on its way.",
            "error": "Something went wrong. Please try again or email me directly.",
            "direct": "or email directly",
            "remote": "Remote-first studio — meeting clients worldwide.",
            "ig": "Instagram",
            "social_aria": "Instagram profile",
        },
        "footer": {
            "tagline": "Interiors with intention.",
            "nav": "Sitemap",
            "legal": "All rights reserved.",
            "based": "Based in Brazil · working worldwide",
        },
        "404": {
            "title": "Page not found",
            "text": "The page you are looking for has moved or no longer exists.",
            "back": "Back to home",
        },
        "blog": {
            "title": "Journal",
            "sub": "Notes on light, colour, and the craft of making rooms feel right.",
            "read_more": "Read article",
            "back": "Back to journal",
            "next": "Next article",
            "prev": "Previous article",
            "other_langs": "Read this article in",
            "by": "By Bruno Vinícius",
            "category_meta": "Category",
        },
    },

    "es": {
        "brand": "Bruno Vinícius",
        "studio": "Diseño de Interiores",
        "nav": {
            "work": "Trabajo",
            "about": "Sobre mí",
            "services": "Servicios",
            "journal": "Revista",
            "contact": "Contacto",
            "cta": "Iniciar un proyecto",
            "view_project": "Ver proyecto",
            "prev_project": "Proyecto anterior",
            "next_project": "Próximo proyecto",
            "other_langs": "Leer en",
            "back_to_work": "Volver al trabajo",
        },
        "meta": {
            "title": "Bruno Vinícius — Estudio de Diseño de Interiores",
            "description": "Diseño de interiores a medida para espacios residenciales y de hostelería en todo el mundo. Interiores serenos, pensados para vivirlos.",
        },
        "hero": {
            "eyebrow": "Estudio de diseño de interiores",
            "h1_before": "Interiores con",
            "h1_em": "intención.",
            "sub": "Diseño espacios residenciales y de hostelería para clientes de todo el mundo: serenos, con capas y pensados para vivirse.",
            "cta_primary": "Iniciar un proyecto",
            "cta_secondary": "Trabajo seleccionado",
            "scroll": "Desplázate",
        },
        "statement": {
            "text": "Las buenas estancias no gritan. Guardan una presencia serena, marcada por la luz, la proporción y esos pequeños detalles que se sienten más de lo que se notan. Ese es el espacio que diseño: uno que se parece a ti, solo que más pensado.",
        },
        "work": {
            "title": "Trabajo seleccionado",
            "sub": "Una pequeña selección de proyectos residenciales y de hostelería, desde reformas integrales hasta e-design a medida.",
            "view_all": "Ver todos los proyectos",
            "filter_all": "Todos",
        },
        "about": {
            "title": "Sobre mí",
            "heading": "Diseñar es una forma de escuchar.",
            "p1": "Soy Bruno Vinícius, diseñador de interiores que trabaja en proyectos residenciales y de hostelería en Europa y América.",
            "p2": "Mi trabajo se mueve entre la contención contemporánea y el detalle cálido y familiar. Los mejores interiores empiezan por cómo debe sentirse un espacio, no por cómo debe verse: la luz, la proporción y los materiales honestos hacen la mayor parte del trabajo.",
            "p3": "Formado en arquitectura y diseño, dirijo un estudio boutique en línea, trabajando con clientes dondequiera que estén y entregando proyectos que viajan bien.",
            "process_title": "Cómo trabajamos",
            "process": [
                {"t": "Descubrir", "d": "Hablamos de cómo vives, trabajas y recibes. Escucho para captar la sensación que quieres que tenga el espacio."},
                {"t": "Diseñar", "d": "Concepto, ambiente, materiales y distribución, desarrollados juntos hasta que resultan inevitables."},
                {"t": "Desarrollar", "d": "Planos técnicos, selección de materiales y coordinación con constructores y artesanos, gestionado de principio a fin."},
                {"t": "Entregar", "d": "Instalación y estilismo, hasta el último objeto. El espacio se entrega listo para vivirse."},
            ],
            "note": "Presupuestos claros, plazos honestos, sin sorpresas.",
        },
        "services": {
            "title": "Servicios",
            "sub": "Seis formas de trabajar juntos, desde una sola estancia hasta un proyecto completo, presencial o en remoto.",
            "items": [
                {"t": "Diseño residencial", "d": "Diseño completo para casas y apartamentos: distribución, materiales y estilismo, del primer boceto a la entrega final."},
                {"t": "Hostelería y comercial", "d": "Restaurantes, boutiques y oficinas diseñados para acoger a las personas y rendir todo el día."},
                {"t": "Cocinas y baños", "d": "Precisos, personales y prácticos: las estancias más usadas, bien resueltas."},
                {"t": "Diseño de iluminación", "d": "Planos de iluminación por capas que cambian el ambiente de una estancia de la mañana a la noche."},
                {"t": "E-design / Online", "d": "Paquetes de diseño completos entregados en remoto, con listas de compra y guía para ejecutarlos en cualquier lugar."},
                {"t": "Consulta de diseño", "d": "Una sesión centrada para resolver una estancia, un proyecto o un problema concreto."},
            ],
        },
        "testimonials": {
            "title": "Buenas palabras",
            "items": [
                {"q": "Bruno escuchó antes de dibujar. El resultado es una casa que por fin se parece a nosotros.", "a": "Renata M.", "r": "Cliente residencial"},
                {"q": "Del concepto a la instalación todo fue sereno, preciso y puntual. Solo la iluminación ya lo cambió todo.", "a": "Thomas L.", "r": "Cliente de hostelería"},
                {"q": "Rediseñamos en remoto desde otro continente. El proceso fue claro y el resultado superó nuestras expectativas.", "a": "Sara y Mark", "r": "Clientes de e-design"},
            ],
        },
        "journal": {
            "title": "Revista",
            "sub": "Notas sobre luz, color y el oficio de hacer que las estancias se sientan bien.",
            "read": "Leer",
            "all": "Todos los artículos",
        },
        "contact": {
            "title": "Iniciar un proyecto",
            "sub": "Cuéntame sobre tu espacio y cómo quieres vivirlo. Respondo en dos días laborables.",
            "name": "Nombre",
            "email": "Correo electrónico",
            "type": "Tipo de proyecto",
            "type_placeholder": "Residencial, hostelería, e-design…",
            "message": "Cuéntame sobre tu proyecto",
            "submit": "Enviar mensaje",
            "sending": "Enviando…",
            "success": "Gracias: tu mensaje está en camino.",
            "error": "Algo salió mal. Inténtalo de nuevo o escríbeme directamente.",
            "direct": "o escribe directamente",
            "remote": "Estudio remoto — trabajando con clientes de todo el mundo.",
            "ig": "Instagram",
            "social_aria": "Perfil de Instagram",
        },
        "footer": {
            "tagline": "Interiores con intención.",
            "nav": "Mapa del sitio",
            "legal": "Todos los derechos reservados.",
            "based": "Con base en Brasil · trabajando en todo el mundo",
        },
        "404": {
            "title": "Página no encontrada",
            "text": "La página que buscas se ha movido o ya no existe.",
            "back": "Volver al inicio",
        },
        "blog": {
            "title": "Revista",
            "sub": "Notas sobre luz, color y el oficio de hacer que las estancias se sientan bien.",
            "read_more": "Leer artículo",
            "back": "Volver a la revista",
            "next": "Siguiente artículo",
            "prev": "Artículo anterior",
            "other_langs": "Lee este artículo en",
            "by": "Por Bruno Vinícius",
            "category_meta": "Categoría",
        },
    },

    "it": {
        "brand": "Bruno Vinícius",
        "studio": "Interior Design",
"nav": {
            "work": "Progetti",
            "about": "Studio",
            "services": "Servizi",
            "journal": "Diario",
            "contact": "Contatti",
            "cta": "Inizia un progetto",
            "view_project": "Vedi progetto",
            "prev_project": "Progetto precedente",
            "next_project": "Progetto successivo",
            "other_langs": "Leggi in",
            "back_to_work": "Torna ai progetti",
        },
        "meta": {
            "title": "Bruno Vinícius — Studio di Interior Design",
            "description": "Interior design su misura per spazi residenziali e dell'ospitalità in tutto il mondo. Interni calmi, stratificati, fatti per essere vissuti.",
        },
        "hero": {
            "eyebrow": "Studio di interior design",
            "h1_before": "Interni con",
            "h1_em": "intenzione.",
            "sub": "Progetto spazi residenziali e dell'ospitalità per clienti in tutto il mondo: calmi, stratificati, fatti per essere vissuti.",
            "cta_primary": "Inizia un progetto",
            "cta_secondary": "Progetti selezionati",
            "scroll": "Scorri",
        },
        "statement": {
            "text": "Le buone stanze non urlano. Racchiudono una presenza quieta, fatta di luce, proporzione e piccoli dettagli che si sentono più di quanto si notino. Questo è lo spazio che progetto: uno che somiglia a te, solo più pensato.",
        },
        "work": {
            "title": "Progetti selezionati",
            "sub": "Una piccola selezione di progetti residenziali e dell'ospitalità, dalle ristrutturazioni complete all'e-design su misura.",
            "view_all": "Vedi tutti i progetti",
            "filter_all": "Tutti",
        },
        "about": {
            "title": "Studio",
            "heading": "Progettare è un modo di ascoltare.",
            "p1": "Sono Bruno Vinícius, interior designer che lavora su progetti residenziali e dell'ospitalità in Europa e nelle Americhe.",
            "p2": "Il mio lavoro si muove tra la sobrietà contemporanea e il dettaglio caldo e familiare. I migliori interni partono da come uno spazio deve sentirsi, non da come deve apparire: luce, proporzione e materiali onesti fanno la maggior parte del lavoro.",
            "p3": "Formatosi tra architettura e design, gestisco uno studio boutique online, seguendo i clienti ovunque siano e consegnando progetti che viaggiano bene.",
            "process_title": "Come lavoriamo",
            "process": [
                {"t": "Scoperta", "d": "Parliamo di come vivi, lavori e ricevi. Ascolto per cogliere la sensazione che vuoi dare allo spazio."},
                {"t": "Progettazione", "d": "Concetto, atmosfera, materiali e distribuzione, sviluppati insieme finché non sembrano inevitabili."},
                {"t": "Sviluppo", "d": "Disegni tecnici, selezione dei materiali e coordinamento con imprese e artigiani, gestiti dall'inizio alla fine."},
                {"t": "Consegna", "d": "Installazione e styling, fino all'ultimo oggetto. Lo spazio viene consegnato pronto da vivere."},
            ],
            "note": "Budget chiari, tempi onesti, nessuna sorpresa.",
        },
        "services": {
            "title": "Servizi",
            "sub": "Sei modi di lavorare insieme, da una singola stanza a un progetto completo, in presenza o a distanza.",
            "items": [
                {"t": "Design residenziale", "d": "Progettazione completa per case e appartamenti: distribuzione, materiali e styling, dal primo schizzo alla consegna finale."},
                {"t": "Ospitalità e commerciale", "d": "Ristoranti, boutique e uffici progettati per accogliere le persone e funzionare tutto il giorno."},
                {"t": "Cucine e bagni", "d": "Precisi, personali e pratici: gli ambienti più usati, risolti nel modo giusto."},
                {"t": "Design dell'illuminazione", "d": "Piani luce stratificati che cambiano l'atmosfera di una stanza dal mattino alla sera."},
                {"t": "E-design / Online", "d": "Pacchetti di design completi consegnati a distanza, con liste d'acquisto e indicazioni applicabili ovunque."},
                {"t": "Consulenza di design", "d": "Una sessione mirata per risolvere una stanza, un progetto o un problema specifico."},
            ],
        },
        "testimonials": {
            "title": "Parole gentili",
            "items": [
                {"q": "Bruno ha ascoltato prima di disegnare. Il risultato è una casa che finalmente somiglia a noi.", "a": "Renata M.", "r": "Cliente residenziale"},
                {"q": "Dal concept all'installazione tutto è stato calmo, preciso e puntuale. Solo l'illuminazione ha cambiato tutto.", "a": "Thomas L.", "r": "Cliente dell'ospitalità"},
                {"q": "Abbiamo ridisegnato a distanza da un altro continente. Il processo è stato chiaro e il risultato ha superato le attese.", "a": "Sara & Mark", "r": "Clienti e-design"},
            ],
        },
        "journal": {
            "title": "Diario",
            "sub": "Note su luce, colore e sul mestiere di far sentire bene le stanze.",
            "read": "Leggi",
            "all": "Tutti gli articoli",
        },
        "contact": {
            "title": "Inizia un progetto",
            "sub": "Raccontami del tuo spazio e di come vuoi viverlo. Rispondo entro due giorni lavorativi.",
            "name": "Nome",
            "email": "Email",
            "type": "Tipo di progetto",
            "type_placeholder": "Residenziale, ospitalità, e-design…",
            "message": "Raccontami del tuo progetto",
            "submit": "Invia messaggio",
            "sending": "Invio…",
            "success": "Grazie: il tuo messaggio è in viaggio.",
            "error": "Qualcosa è andato storto. Riprova o scrivimi direttamente.",
            "direct": "oppure scrivi direttamente",
            "remote": "Studio remoto — clienti in tutto il mondo.",
            "ig": "Instagram",
            "social_aria": "Profilo Instagram",
        },
        "footer": {
            "tagline": "Interni con intenzione.",
            "nav": "Mappa del sito",
            "legal": "Tutti i diritti riservati.",
            "based": "Base in Brasile · lavoro in tutto il mondo",
        },
        "404": {
            "title": "Pagina non trovata",
            "text": "La pagina che cerchi si è spostata o non esiste più.",
            "back": "Torna alla home",
        },
        "blog": {
            "title": "Diario",
            "sub": "Note su luce, colore e sul mestiere di far sentire bene le stanze.",
            "read_more": "Leggi l'articolo",
            "back": "Torna al diario",
            "next": "Articolo successivo",
            "prev": "Articolo precedente",
            "other_langs": "Leggi questo articolo in",
            "by": "Di Bruno Vinícius",
            "category_meta": "Categoria",
        },
    },

    "fr": {
        "brand": "Bruno Vinícius",
        "studio": "Design d'intérieur",
        "nav": {
            "work": "Projets",
            "about": "Studio",
            "services": "Services",
            "journal": "Journal",
            "contact": "Contact",
            "cta": "Lancer un projet",
            "view_project": "Voir le projet",
            "prev_project": "Projet précédent",
            "next_project": "Projet suivant",
            "other_langs": "Lire en",
            "back_to_work": "Retour aux projets",
        },
        "meta": {
            "title": "Bruno Vinícius — Studio de Design d'intérieur",
            "description": "Design d'intérieur sur mesure pour les espaces résidentiels et hôteliers du monde entier. Des intérieurs calmes, riches en couches, faits pour être vécus.",
        },
        "hero": {
            "eyebrow": "Studio de design d'intérieur",
            "h1_before": "Des intérieurs avec",
            "h1_em": "une intention.",
            "sub": "Je conçois des espaces résidentiels et hôteliers pour des clients du monde entier : calmes, riches en couches, faits pour être vécus.",
            "cta_primary": "Lancer un projet",
            "cta_secondary": "Projets choisis",
            "scroll": "Défiler",
        },
        "statement": {
            "text": "Les belles pièces ne crient pas. Elles dégagent une présence calme, faite de lumière, de proportion et de petits détails qui se ressentent plus qu'ils ne se remarquent. C'est ce genre d'espace que je conçois : un espace qui vous ressemble, simplement plus réfléchi.",
        },
        "work": {
            "title": "Projets choisis",
            "sub": "Une petite sélection de projets résidentiels et hôteliers, de la rénovation complète à l'e-design sur mesure.",
            "view_all": "Voir tous les projets",
            "filter_all": "Tous",
        },
        "about": {
            "title": "Studio",
            "heading": "Concevoir, c'est une façon d'écouter.",
            "p1": "Je suis Bruno Vinícius, designer d'intérieur travaillant sur des projets résidentiels et hôteliers en Europe et dans les Amériques.",
            "p2": "Mon travail se situe entre la retenue contemporaine et le détail chaleureux et familier. Les meilleurs intérieurs partent de ce qu'un espace doit faire ressentir, pas de ce qu'il doit montrer : la lumière, la proportion et les matériaux honnêtes font l'essentiel du travail.",
            "p3": "Formé entre architecture et design, je dirige un studio boutique en ligne, en travaillant avec des clients où qu'ils soient et en livrant des projets qui voyagent bien.",
            "process_title": "Notre façon de travailler",
            "process": [
                {"t": "Découvrir", "d": "Nous parlons de la façon dont vous vivez, travaillez et recevez. J'écoute pour saisir la sensation que vous voulez donner à l'espace."},
                {"t": "Concevoir", "d": "Concept, ambiance, matériaux et plan, développés ensemble jusqu'à ce que tout paraisse évident."},
                {"t": "Développer", "d": "Plans techniques, sélection des matériaux et coordination avec les artisans, gérés de bout en bout."},
                {"t": "Livrer", "d": "Installation et stylisme, jusqu'au dernier objet. L'espace est livré prêt à vivre."},
            ],
            "note": "Budgets clairs, délais honnêtes, aucune surprise.",
        },
        "services": {
            "title": "Services",
            "sub": "Six façons de travailler ensemble, d'une pièce unique à un projet complet, en personne ou à distance.",
            "items": [
                {"t": "Design résidentiel", "d": "Conception complète pour maisons et appartements : plan, matériaux et stylisme, du premier croquis à la livraison finale."},
                {"t": "Hôtellerie et commercial", "d": "Restaurants, boutiques et bureaux conçus pour accueillir les gens et performer toute la journée."},
                {"t": "Cuisines et salles de bain", "d": "Précis, personnels et pratiques : les pièces les plus utilisées, bien résolues."},
                {"t": "Conception lumière", "d": "Des plans d'éclairage en couches qui changent l'ambiance d'une pièce du matin au soir."},
                {"t": "E-design / À distance", "d": "Des packs de design complets livrés à distance, avec listes d'achat et indications à exécuter partout."},
                {"t": "Consultation design", "d": "Une session ciblée pour résoudre une pièce, un projet ou un problème précis."},
            ],
        },
        "testimonials": {
            "title": "Beaux mots",
            "items": [
                {"q": "Bruno a écouté avant de dessiner. Le résultat est une maison qui nous ressemble enfin.", "a": "Renata M.", "r": "Cliente résidentielle"},
                {"q": "Du concept à l'installation, tout a été calme, précis et ponctuel. L'éclairage seul a tout changé.", "a": "Thomas L.", "r": "Client hôtelier"},
                {"q": "Nous avons redessiné à distance depuis un autre continent. Le processus était clair et le résultat a dépassé nos attentes.", "a": "Sara & Mark", "r": "Clients e-design"},
            ],
        },
        "journal": {
            "title": "Journal",
            "sub": "Notes sur la lumière, la couleur et l'art de faire en sorte que les pièces se sentent bien.",
            "read": "Lire",
            "all": "Tous les articles",
        },
        "contact": {
            "title": "Lancer un projet",
            "sub": "Parlez-moi de votre espace et de la façon dont vous voulez y vivre. Je réponds sous deux jours ouvrés.",
            "name": "Nom",
            "email": "Email",
            "type": "Type de projet",
            "type_placeholder": "Résidentiel, hôtellerie, e-design…",
            "message": "Parlez-moi de votre projet",
            "submit": "Envoyer le message",
            "sending": "Envoi…",
            "success": "Merci — votre message est en route.",
            "error": "Une erreur est survenue. Réessayez ou écrivez-moi directement.",
            "direct": "ou écrivez-moi directement",
            "remote": "Studio à distance — clients dans le monde entier.",
            "ig": "Instagram",
            "social_aria": "Profil Instagram",
        },
        "footer": {
            "tagline": "Des intérieurs avec intention.",
            "nav": "Plan du site",
            "legal": "Tous droits réservés.",
            "based": "Basé au Brésil · travail dans le monde entier",
        },
        "404": {
            "title": "Page introuvable",
            "text": "La page que vous cherchez a été déplacée ou n'existe plus.",
            "back": "Retour à l'accueil",
        },
        "blog": {
            "title": "Journal",
            "sub": "Notes sur la lumière, la couleur et l'art de faire en sorte que les pièces se sentent bien.",
            "read_more": "Lire l'article",
            "back": "Retour au journal",
            "next": "Article suivant",
            "prev": "Article précédent",
            "other_langs": "Lire cet article en",
            "by": "Par Bruno Vinícius",
            "category_meta": "Catégorie",
        },
    },

    "pt": {
        "brand": "Bruno Vinícius",
        "studio": "Design de Interiores",
        "nav": {
            "work": "Projetos",
            "about": "Sobre",
            "services": "Serviços",
            "journal": "Blog",
            "contact": "Contato",
            "cta": "Iniciar um projeto",
            "view_project": "Ver projeto",
            "prev_project": "Projeto anterior",
            "next_project": "Próximo projeto",
            "other_langs": "Ler em",
            "back_to_work": "Voltar aos projetos",
        },
        "meta": {
            "title": "Bruno Vinícius — Estúdio de Design de Interiores",
            "description": "Design de interiores sob medida para espaços residenciais e de hospitalidade no mundo todo. Interiores calmos, em camadas, feitos para serem vividos.",
        },
        "hero": {
            "eyebrow": "Estúdio de design de interiores",
            "h1_before": "Interiores com",
            "h1_em": "intenção.",
            "sub": "Desenho espaços residenciais e de hospitalidade para clientes no mundo todo. calmos, em camadas e feitos para serem vividos.",
            "cta_primary": "Iniciar um projeto",
            "cta_secondary": "Projetos selecionados",
            "scroll": "Role",
        },
        "statement": {
            "text": "Bons ambientes não gritam. Eles guardam uma presença calma, moldada pela luz, pela proporção e pelos pequenos detalhes que se sentem mais do que se notam. Esse é o tipo de espaço que eu projeto: um que parece com você, só que mais pensado.",
        },
        "work": {
            "title": "Projetos selecionados",
            "sub": "Uma pequena seleção de projetos residenciais e de hospitalidade. de reformas completas ao e-design sob medida.",
            "view_all": "Ver todos os projetos",
            "filter_all": "Todos",
        },
        "about": {
            "title": "Sobre",
            "heading": "Projetar é uma forma de escutar.",
            "p1": "Sou Bruno Vinícius, designer de interiores trabalhando em projetos residenciais e de hospitalidade na Europa e nas Américas.",
            "p2": "Meu trabalho transita entre a contenção contemporânea e o detalhe quente e familiar. Os melhores interiores começam por como um espaço deve fazer você se sentir, não por como deve parecer — a luz, a proporção e os materiais honestos fazem a maior parte do trabalho.",
            "p3": "Formado entre arquitetura e design, comando um estúdio boutique online, atendendo clientes onde estiverem e entregando projetos que viajam bem.",
            "process_title": "Como trabalhamos",
            "process": [
                {"t": "Descobrir", "d": "Conversamos sobre como você vive, trabalha e recebe. Eu escuto para captar a sensação que o espaço deve carregar."},
                {"t": "Projetar", "d": "Conceito, clima, materiais e layout, desenvolvidos juntos até parecer inevitável."},
                {"t": "Desenvolver", "d": "Desenhos técnicos, seleção de materiais e coordenação com construtores e artesãos, gerenciados de ponta a ponta."},
                {"t": "Entregar", "d": "Instalação e styling, até o último objeto. O espaço é entregue pronto para ser vivido."},
            ],
            "note": "Orçamentos claros, prazos honestos, nenhuma surpresa.",
        },
        "services": {
            "title": "Serviços",
            "sub": "Seis formas de trabalharmos juntos. de um único cômodo a um projeto completo, presencial ou remoto.",
            "items": [
                {"t": "Design residencial", "d": "Projeto completo para casas e apartamentos — layout, materiais e styling, do primeiro esboço à entrega final."},
                {"t": "Hospitalidade e comercial", "d": "Restaurantes, boutiques e escritórios projetados para acolher pessoas e funcionar o dia inteiro."},
                {"t": "Cozinhas e banheiros", "d": "Precisos, pessoais e práticos — os cômodos mais usados, bem resolvidos."},
                {"t": "Design de iluminação", "d": "Planos de iluminação em camadas que mudam o clima de um ambiente da manhã à noite."},
                {"t": "E-design / Online", "d": "Pacotes de design completos entregues remotamente, com listas de compra e orientação para executar em qualquer lugar."},
                {"t": "Consultoria de design", "d": "Uma sessão focada para resolver um cômodo, um projeto ou um problema específico."},
            ],
        },
        "testimonials": {
            "title": "Quem já viveu",
            "items": [
                {"q": "O Bruno escutou antes de desenhar. O resultado é uma casa que finalmente parece com a gente.", "a": "Renata M.", "r": "Cliente residencial"},
                {"q": "Do conceito à instalação, tudo foi calmo, preciso e no prazo. Só a iluminação já mudou tudo.", "a": "Thomas L.", "r": "Cliente de hospitalidade"},
                {"q": "Redesenhamos remotamente de outro continente. O processo foi claro e o resultado superou as expectativas.", "a": "Sara & Mark", "r": "Clientes de e-design"},
            ],
        },
        "journal": {
            "title": "Blog",
            "sub": "Anotações sobre luz, cor e o ofício de fazer ambientes se sentirem bem.",
            "read": "Ler",
            "all": "Todos os artigos",
        },
        "contact": {
            "title": "Iniciar um projeto",
            "sub": "Conte sobre seu espaço e como você quer vivê-lo. Respondo em até dois dias úteis.",
            "name": "Nome",
            "email": "E-mail",
            "type": "Tipo de projeto",
            "type_placeholder": "Residencial, hospitalidade, e-design…",
            "message": "Conte sobre o seu projeto",
            "submit": "Enviar mensagem",
            "sending": "Enviando…",
            "success": "Obrigado — sua mensagem está a caminho.",
            "error": "Algo deu errado. Tente novamente ou escreva direto para mim.",
            "direct": "ou escreva diretamente",
            "remote": "Estúdio remoto — atendendo clientes no mundo todo.",
            "ig": "Instagram",
            "social_aria": "Perfil no Instagram",
        },
        "footer": {
            "tagline": "Interiores com intenção.",
            "nav": "Mapa do site",
            "legal": "Todos os direitos reservados.",
            "based": "Base no Brasil · atuação no mundo todo",
        },
        "404": {
            "title": "Página não encontrada",
            "text": "A página que você procura mudou de lugar ou não existe mais.",
            "back": "Voltar ao início",
        },
        "blog": {
            "title": "Blog",
            "sub": "Anotações sobre luz, cor e o ofício de fazer ambientes se sentirem bem.",
            "read_more": "Ler artigo",
            "back": "Voltar ao blog",
            "next": "Próximo artigo",
            "prev": "Artigo anterior",
            "other_langs": "Leia este artigo em",
            "by": "Por Bruno Vinícius",
            "category_meta": "Categoria",
        },
    },
}

PROJECTS = [
    {
        "id": "casa-aurora",
        "image": "project-sala.jpg",
        "tall": True,
        "name": {"en": "Casa Aurora", "es": "Casa Aurora", "it": "Casa Aurora", "fr": "Casa Aurora", "pt": "Casa Aurora"},
        "cat": {"en": "Residential", "es": "Residencial", "it": "Residenziale", "fr": "Résidentiel", "pt": "Residencial"},
        "loc": {"en": "São Paulo", "es": "São Paulo", "it": "São Paulo", "fr": "São Paulo", "pt": "São Paulo"},
        "year": "2026",
        "blurb": {
            "en": "A serene apartment reworked around natural light and tactile materials.",
            "es": "Un sereno apartamento reformado en torno a la luz natural y los materiales táctiles.",
            "it": "Un appartamento sereno riprogettato intorno alla luce naturale e ai materiali tattili.",
            "fr": "Un appartement serein repensé autour de la lumière naturelle et des matières tactiles.",
            "pt": "Um apartamento sereno redesenhado em torno da luz natural e de materiais táteis.",
        },
    },
    {
        "id": "alba-house",
        "image": "project-quarto.jpg",
        "tall": True,
        "name": {"en": "Alba House", "es": "Alba House", "it": "Alba House", "fr": "Alba House", "pt": "Alba House"},
        "cat": {"en": "Residential", "es": "Residencial", "it": "Residenziale", "fr": "Résidentiel", "pt": "Residencial"},
        "loc": {"en": "Lisbon", "es": "Lisboa", "it": "Lisbona", "fr": "Lisbonne", "pt": "Lisboa"},
        "year": "2025",
        "blurb": {
            "en": "Warm minimalism for a young family, balancing openness with intimacy.",
            "es": "Minimalismo cálido para una familia joven, equilibrando apertura e intimidad.",
            "it": "Minimalismo caldo per una giovane famiglia, tra apertura e intimità.",
            "fr": "Un minimalisme chaleureux pour une jeune famille, entre ouverture et intimité.",
            "pt": "Minimalismo quente para uma jovem família, equilibrando amplitude e intimidade.",
        },
    },
    {
        "id": "bistro-melo",
        "image": "project-restaurante.jpg",
        "tall": False,
        "name": {"en": "Bistro Melo", "es": "Bistro Melo", "it": "Bistro Melo", "fr": "Bistro Melo", "pt": "Bistro Melo"},
        "cat": {"en": "Hospitality", "es": "Hostelería", "it": "Ospitalità", "fr": "Hôtellerie", "pt": "Hospitalidade"},
        "loc": {"en": "Porto", "es": "Oporto", "it": "Porto", "fr": "Porto", "pt": "Porto"},
        "year": "2025",
        "blurb": {
            "en": "A compact restaurant interior where lighting sets the evening mood.",
            "es": "Un interior de restaurante compacto donde la iluminación marca el ambiente nocturno.",
            "it": "Un ristorante compatto dove l'illuminazione definisce l'atmosfera serale.",
            "fr": "Un restaurant compact où l'éclairage installe l'ambiance du soir.",
            "pt": "Um restaurante compacto onde a iluminação define o clima da noite.",
        },
    },
    {
        "id": "villa-serena",
        "image": "project-cozinha.jpg",
        "tall": False,
        "name": {"en": "Villa Serena", "es": "Villa Serena", "it": "Villa Serena", "fr": "Villa Serena", "pt": "Villa Serena"},
        "cat": {"en": "Residential", "es": "Residencial", "it": "Residenziale", "fr": "Résidentiel", "pt": "Residencial"},
        "loc": {"en": "Lake Como", "es": "Lago de Como", "it": "Lago di Como", "fr": "Lac de Côme", "pt": "Lago de Como"},
        "year": "2024",
        "blurb": {
            "en": "Layered elegance for a lakeside retreat, grounded in quiet tones.",
            "es": "Elegancia en capas para un refugio junto al lago, anclada en tonos serenos.",
            "it": "Eleganza a strati per un rifugio sul lago, radicata in toni quieti.",
            "fr": "Une élégance en couches pour une retraite au bord du lac, ancrée dans des tons calmes.",
            "pt": "Elegância em camadas para um refúgio à beira do lago, ancorada em tons serenos.",
        },
    },
    {
        "id": "atelier-norte",
        "image": "project-escritorio.jpg",
        "tall": False,
        "name": {"en": "Atelier Norte", "es": "Atelier Norte", "it": "Atelier Norte", "fr": "Atelier Norte", "pt": "Atelier Norte"},
        "cat": {"en": "Workspace", "es": "Espacio de trabajo", "it": "Spazio di lavoro", "fr": "Espace de travail", "pt": "Espaço de trabalho"},
        "loc": {"en": "Copenhagen", "es": "Copenhague", "it": "Copenaghen", "fr": "Copenhague", "pt": "Copenhague"},
        "year": "2024",
        "blurb": {
            "en": "A calm studio for a design practice — flexible, focused, humane.",
            "es": "Un estudio sereno para una práctica de diseño: flexible, enfocado y humano.",
            "it": "Uno studio calmo per una pratica di design: flessibile, focalizzato, umano.",
            "fr": "Un studio calme pour une pratique de design — flexible, concentré, humain.",
            "pt": "Um estúdio calmo para uma prática de design — flexível, focado, humano.",
        },
    },
    {
        "id": "suite-no-7",
        "image": "project-luminaria.jpg",
        "tall": True,
        "name": {"en": "Suite No. 7", "es": "Suite No. 7", "it": "Suite No. 7", "fr": "Suite No. 7", "pt": "Suíte Nº 7"},
        "cat": {"en": "Hospitality", "es": "Hostelería", "it": "Ospitalità", "fr": "Hôtellerie", "pt": "Hospitalidade"},
        "loc": {"en": "Milan", "es": "Milán", "it": "Milano", "fr": "Milan", "pt": "Milão"},
        "year": "2023",
        "blurb": {
            "en": "A boutique hotel suite exploring depth, texture, and restful light.",
            "es": "Una suite de hotel boutique que explora profundidad, textura y luz reparadora.",
            "it": "Una suite di hotel boutique che esplora profondità, texture e luce riposante.",
            "fr": "Une suite d'hôtel boutique qui explore la profondeur, la texture et la lumière reposante.",
            "pt": "Uma suíte de hotel boutique explorando profundidade, textura e luz repousante.",
        },
    },
]

CONTACT = {
    "email": "hello@brunovinicius.design",
    "instagram": "brunovinicius.interiors",
    "instagram_url": "https://instagram.com/brunovinicius.interiors",
    "reply_time": "48h",
}

IMAGES = {
    "hero": "/assets/img/hero.jpg",
    "og": "/assets/img/og.jpg",
    "about": "/assets/img/studio-1.jpg",
    "statement_thumb": "/assets/img/detalhe-textura.jpg",
    "marble": "/assets/img/detalhe-marmore.jpg",
    "velvet": "/assets/img/detalhe-veludo.jpg",
}
