# -*- coding: utf-8 -*-
"""Articles de blog — FRANÇAIS. 7 articles, optimisés SEO pour la niche de la décoration d’intérieur."""

BLOG = [
    {
        "slug": "whats-new-in-interiors",
        "date": "2026-08-01",
        "category": "Tendances",
        "read_time": 6,
        "image": "blog-4.jpg",
        "title": "Ce qui se fait en décoration en ce moment",
        "excerpt": "Neutres chaleureux, lumière sculpturale et mobilier qui a sa raison d’être : un petit guide de terrain sur la direction que prend l’intérieur cette saison.",
        "meta": "Les tendances déco à suivre : neutres chaleureux, éclairage sculptural, mobilier à hauteur humaine et retour de l’artisanat. Carnet de Bruno Vinícius.",
        "blocks": [
            {"t": "p", "c": "Une tendance n’est utile que si elle vous aide à prendre une décision. Tout ce qui suit est une direction, pas une règle — prenez ce qui soutient la façon dont vous vivez vraiment, et laissez le reste."},
            {"t": "h2", "c": "Les neutres chaleureux reviennent, et ce n’est pas du beige"},
            {"t": "p", "c": "Les gris froids qui ont dominé les intérieurs pendant une décennie cèdent la place à des neutres plus chauds et plus profonds — pensez pierre, sable, champignon, olive. La différence compte : les neutres chaleureux captent davantage la lumière et photographient mieux, et ils mettent les personnes en valeur dans une pièce."},
            {"t": "p", "c": "Pour les employer sans tomber dans la platitude, jouez sur le contraste des matières plutôt que celui des couleurs. Un mur couleur sable devient riche lorsqu’il rencontre un canapé en lin, une table en travertin et un plancher de noyer foncé."},
            {"t": "h2", "c": "L’éclairage est devenu la pièce maîtresse"},
            {"t": "p", "c": "Les suspensions ne sont plus de simples accessoires. Les verres sculpturaux et les luminaires soufflés à la main reprennent le rôle que tenait autrefois le lustre — ce que l’on remarque en premier en entrant dans une pièce. Le principe est le même que celui que pratiquent depuis des décennies les grandes maisons d’éclairage : la lumière comme matière première, tout le reste s’organisant autour d’elle."},
            {"t": "quote", "c": "La lumière est la première matière que je choisis. Tout le reste — la couleur, le mobilier, l’agencement — se négocie autour d’elle."},
            {"t": "h2", "c": "Un mobilier qui a sa raison d’être"},
            {"t": "p", "c": "L’autre signal est net : on s’éloigne des ensembles. Les salons assortis en trois pièces disparaissent au profit de pièces singulières et bien choisies, qui peuvent voyager avec vous — une chaise sculpturale, une table qui se transmet, une lampe que l’on gardera vingt ans."},
            {"t": "h2", "c": "Suivre la nouveauté sans se perdre"},
            {"t": "p", "c": "Il existe deux bons endroits pour repérer les nouveautés avant qu’elles n’arrivent en magasin. Le premier, ce sont les créateurs et ateliers indépendants, qui proposent de petites séries d’objets honnêtes. Le second, les plateformes de financement participatif, où les designers indépendants lancent directement mobilier, éclairage et accessoires — souvent une saison avant le commerce, et généralement avec l’histoire du design encore attachée."},
            {"t": "p", "c": "Ni l’un ni l’autre ne remplace la visite d’un showroom. Mais tous deux sont excellents pour repérer ces petites idées précises — un nouveau pied de table, une nouvelle façon de plier la lumière, qui rendent une pièce actuelle sans air de catalogue."},
            {"t": "h2", "c": "En résumé"},
            {"t": "ul", "c": [
                "Choisissez des neutres profonds et chaleureux, et ajoutez de la richesse par la texture, pas par la couleur.",
                "Confiez à un seul luminaire le rôle de pièce maîtresse — c’est là qu’il faut investir.",
                "Achetez des pièces singulières qui ont une histoire, plutôt que des ensembles assortis.",
                "Suivez les créateurs et les lancements indépendants pour repérer les idées qui arrivent tôt.",
            ]},
            {"t": "p", "c": "Les tendances vont et viennent. Si vous concevez une pièce qui soutient vos habitudes et vous met à l’aise, elle aura l’air juste cette saison comme dans dix saisons."},
        ],
    },
    {
        "slug": "how-to-choose-an-interior-design-style",
        "date": "2026-07-14",
        "category": "Notions de base",
        "read_time": 6,
        "image": "blog-5.jpg",
        "title": "Choisir un style d’intérieur qui correspond à votre vie",
        "excerpt": "La plupart des quiz de style passent à côté de l’essentiel. La bonne direction vient de votre façon de vivre, pas de Pinterest. Une méthode concrète pour trouver la vôtre.",
        "meta": "Comment choisir un style de décoration : une démarche concrète fondée sur votre façon de vivre, de travailler et de recevoir. plutôt que sur Pinterest ou les quiz de style.",
        "blocks": [
            {"t": "p", "c": "Les clients arrivent souvent avec une douzaine d’images sauvegardées et une expression empruntée à un magazine : « scandinave », « organique moderne », « luxe discret ». Aucune n’est fausse. Ce ne sont que des points de départ, et la plupart décrivent la même impulsion de fond : un espace qui respire le calme et l’honnêteté."},
            {"t": "h2", "c": "Commencez par le comportement, pas par le vocabulaire"},
            {"t": "p", "c": "Avant de penser aux matières ou aux couleurs, répondez honnêtement à trois questions. Comment utilisez-vous réellement la pièce, heure par heure ? Qui y partage votre vie, et à quelle fréquence ? Et comment voulez-vous vous sentir en y entrant — reposé, stimulé, accueilli, concentré ? Le style est la réponse à ces questions, traduite en forme physique. Tout le reste est de la décoration."},
            {"t": "h2", "c": "Séparez ce que vous aimez de ce avec quoi vous voulez vivre"},
            {"t": "p", "c": "C'est la distinction qui compte. Un hall d’hôtel peut être superbe et rester un mauvais modèle pour votre salon, car un hôtel est conçu pour un séjour de trente minutes. Votre maison, elle, est conçue pour une décennie de soirées ordinaires. Rassemblez les images que vous aimez, puis divisez-les en deux listes : inspirantes, et réellement vivables. Leur intersection, c’est votre style."},
            {"t": "quote", "c": "Un style qui vous demande de changer votre façon de vivre ne survivra pas au contact de votre vie."},
            {"t": "h2", "c": "Travaillez à partir d’une seule référence forte"},
            {"t": "p", "c": "Dans l’intersection, choisissez une direction comme ancre — la palette ou la pièce clé dont vous êtes sûr, et laissez tout le reste se négocier autour d’elle. Les pièces qui semblent indécises ont généralement deux ou trois références fortes qui se tirent dessus. Une seule ancre, appliquée avec constance, fait qu’une pièce semble conçue plutôt que décorée."},
            {"t": "h2", "c": "Une petite check-list"},
            {"t": "ul", "c": [
                "Notez comment la pièce est utilisée au fil d’une semaine normale.",
                "Constituez un dossier d’images ; séparez-le entre « inspirant » et « vivable ».",
                "Choisissez une ancre — une palette, une matière ou une seule pièce.",
                "Testez l’ancre contre vos habitudes quotidiennes, pas contre une photo.",
                "Autorisez-vous à emprunter un seul détail qui vous plaît, sans raison.",
            ]},
            {"t": "p", "c": "Dans le doute, privilégiez la simplicité à la tendance. Il est plus facile d’ajouter de la personnalité à une base calme que de la soustraire à une base chargée — et c’est dans cette base calme que la plupart des gens finissent par vouloir vivre."},
        ],
    },
    {
        "slug": "the-quiet-power-of-lighting",
        "date": "2026-06-28",
        "category": "Éclairage",
        "read_time": 7,
        "image": "blog-3.jpg",
        "title": "La puissance discrète de la lumière : le guide d’un architecte d’intérieur",
        "excerpt": "La lumière décide de ce qu’une pièce ressent, pas de ce qu’elle montre. Trois strates, cinq erreurs, et comment réussir chez soi.",
        "meta": "Guide de l’éclairage intérieur : les trois strates de la lumière, les erreurs d’éclairage les plus fréquentes et comment créer une lumière qui change l’ambiance d’une pièce.",
        "blocks": [
            {"t": "p", "c": "On se souvient du mobilier, on oublie la lumière. Or c’est elle qui rend une pièce généreuse à sept heures du soir et apaisante à onze heures. La plupart des intérieurs sont conçus pour ce qu’ils montrent en photo ; ceux qui semblent justes sont conçus autour de ce qu’ils font à différentes heures de la journée."},
            {"t": "h2", "c": "Les trois strates"},
            {"t": "p", "c": "Un bon éclairage est rarement un seul luminaire. Ce sont trois strates qui travaillent ensemble, chacune avec un rôle distinct :"},
            {"t": "ul", "c": [
                "Ambiance: une lumière douce et homogène qui remplit la pièce sans éblouir. Éclairage encastré ou indirect, varié, autour de 2 700 K.",
                "Travail: une lumière ciblée là où vous lisez, cuisinez ou travaillez. Une bonne lampe de lecture ou une bande sous les meubles fait plus que vous ne le croyez.",
                "Accent: la lumière qui attire l’œil : un luminaire pour tableau, un éclairage mural, une pièce qui rayonne plutôt qu’elle n’inonde.",
            ]},
            {"t": "h2", "c": "L’interrupteur dont vous vous servirez vraiment"},
            {"t": "p", "c": "L’amélioration la plus efficace dans n’importe quelle pièce, c’est un variateur sur le circuit d’ambiance. C’est peu coûteux, et cela double silencieusement le nombre d’ambiances qu’une pièce peut tenir. Vif pour les matins et le travail, bas pour les soirées, entre les deux pour recevoir. Les pièces qui n’ont qu’un seul niveau de lumière semblent soit cliniques, soit sombres."},
            {"t": "quote", "c": "Une pièce n’est pas la même à six heures du matin et à dix heures du soir. Son éclairage doit pouvoir changer d’avis."},
            {"t": "h2", "c": "Cinq erreurs qui vieillissent une pièce"},
            {"t": "ul", "c": [
                "Un seul plafonnier sans variateur — le plus sûr moyen de donner à une pièce l’air d’une salle d’attente.",
                "Un éclairage uniquement dirigé vers le bas. La lumière murale et de sol, rebondie sur les surfaces, allonge les plafonds et adoucit les visages.",
                "Du blanc froid dans les pièces à vivre. Réservez le 4 000 K et plus aux espaces techniques ; gardez les salons chauds.",
                "Aucune lumière à hauteur d’homme. Une lampe à hauteur des yeux, assis, change tout.",
                "Oublier les luminaires qu’on voit lorsqu’ils sont éteints. Une belle pièce avec un luminaire en plastique bon marché est une contradiction.",
            ]},
            {"t": "h2", "c": "Où investir"},
            {"t": "p", "c": "Si le budget autorise un seul achat généreux dans une pièce, faites-en le luminaire que l’on voit en entrant — la suspension ou l’applique qui porte la strate d’accent. C’est la pièce qui fait le plus de travail, et celle dont on vous posera des questions."},
        ],
    },
    {
        "slug": "small-spaces-big-impact",
        "date": "2026-06-02",
        "category": "Espaces",
        "read_time": 6,
        "image": "blog-1.jpg",
        "title": "Petits espaces, grand effet : concevoir des intérieurs compacts",
        "excerpt": "Les petites pièces échouent à cause de l’encombrement, pas de leur taille. Cinq principes pour rendre un espace compact généreux sans déplacer un mur.",
        "meta": "Principes de décoration pour petits espaces : lumière, échelle, rangements et une pièce forte pour rendre les intérieurs compacts généreux.",
        "blocks": [
            {"t": "p", "c": "Une petite pièce n’a rarement besoin d’être plus grande. Elle a besoin de moins de choses, mieux choisies, et d’une idée plus claire de ce à quoi elle sert. Presque tous les projets compacts que je mène s’améliorent le jour où l’on retire quelque chose plutôt que d’ajouter."},
            {"t": "h2", "c": "Une fonction par pièce, énoncée honnêtement"},
            {"t": "p", "c": "Un séjour-cuisine ouvert qui veut être à la fois salle à manger, bureau, cinéma et salle de jeux ne sera finalement aucun d’entre eux. Donnez à chaque zone un rôle unique et clair, et laissez l’espace respirer autour. Si un coin n’a pas de fonction définie, laissez-le vide — le vide est un luxe, surtout dans les petites maisons."},
            {"t": "h2", "c": "Laissez la lumière faire le travail spatial"},
            {"t": "p", "c": "La lumière est le moyen le moins cher d’agrandir une pièce. Gardez les fenêtres dégagées de rideaux lourds, adoptez des tons de mur pâles qui réfléchissent la lumière plutôt que de l’absorber, et faites rebondir la lumière sur le plafond et les murs au lieu d’éclairer d’un seul point. Une petite pièce qui reçoit une lumière douce et indirecte paraît plus grande qu’une grande pièce dans l’ombre."},
            {"t": "quote", "c": "Dans un petit espace, chaque décision est un échange. Le secret, c’est de savoir à quoi renoncer."},
            {"t": "h2", "c": "L’échelle change tout"},
            {"t": "p", "c": "Une erreur fréquente consiste à acheter du mobilier trop petit, en espérant que la pièce semblera plus grande. C’est l’inverse qui se produit. Un canapé compact aux proportions justes, un tapis qui ancre la zone, et une pièce généreuse — une chaise, une table, une lampe, donnent à l’œil une échelle pour lire la pièce. Quand tout est petit, tout paraît petit."},
            {"t": "h2", "c": "Des rangements qui disparaissent"},
            {"t": "p", "c": "Le bruit visuel d’une petite maison vient surtout d’objets qui n’ont pas de maison. Les rangements intégrés, peints dans la couleur du mur, suppriment le désordre à la source. Donnez à chaque catégorie d’objets une place attitrée — chaussures, manteaux, papiers, câbles, et la pièce elle-même commence à paraître plus grande."},
            {"t": "h2", "c": "Les cinq principes"},
            {"t": "ul", "c": [
                "Donnez à chaque zone un rôle unique ; laissez un coin vide, volontairement.",
                "Maximisez la lumière naturelle et gardez des tons de mur réfléchissants.",
                "Achetez du mobilier à la bonne échelle, et investissez dans une pièce forte.",
                "Dissimulez les rangements dans l’architecture plutôt que d’ajouter du mobilier.",
                "Éditez sans complaisance : tout ce qui est visible doit gagner sa place.",
            ]},
        ],
    },
    {
        "slug": "color-as-a-tool",
        "date": "2026-05-12",
        "category": "Couleur",
        "read_time": 6,
        "image": "blog-2.jpg",
        "title": "La couleur comme outil : construire une palette qui fonctionne",
        "excerpt": "Oubliez l’idée d’assortir le canapé au tapis. La couleur fonctionne comme un système. lumière, profondeur, et un seul geste fort. Comment bâtir une palette qui tient debout.",
        "meta": "Comment construire une palette de couleurs d’intérieur : la règle 60-30-10, la lumière chaude ou froide, la saturation et un seul accent fort, expliqués simplement.",
        "blocks": [
            {"t": "p", "c": "La plupart des gens choisissent la couleur comme on choisit une tenue qu’on adore en photo — et s’étonnent ensuite que le résultat ne tienne pas debout. La couleur, dans une pièce, fonctionne comme un système, avec une hiérarchie, et le système importe davantage qu’aucune couleur en particulier."},
            {"t": "h2", "c": "Commencez par la lumière de la pièce, pas par la tendance"},
            {"t": "p", "c": "La même peinture se lit différemment sous une lumière orientée au nord, sous le soleil couchant de l’ouest ou sous des ampoules chaudes. Une pièce exposée au nord a besoin de tons chauds pour sembler vivante ; une pièce baignée de soleil peut porter des tons plus froids. Avant d’échantillonner les couleurs, observez la lumière : d’où elle vient, comment elle évolue dans la journée, et si vos ampoules sont chaudes ou froides."},
            {"t": "h2", "c": "La structure 60-30-10"},
            {"t": "ul", "c": [
                "60 %: le ton dominant : murs, sol, et les plus grandes surfaces. Gardez-le discret.",
                "30 %: le ton secondaire : le canapé, la menuiserie, le gros mobilier. En dialogue avec le premier.",
                "10 %: l’accent : coussins, une chaise, un tapis, une œuvre. C’est là que vit la personnalité, et il doit rester un actionnaire minoritaire.",
            ]},
            {"t": "quote", "c": "Une palette n’est pas une collection de couleurs préférées. C’est un ensemble de couleurs qui ont accepté de travailler ensemble."},
            {"t": "h2", "c": "Un seul geste fort vaut mieux que cinq jolis"},
            {"t": "p", "c": "Les pièces qui semblent indécises ont généralement plusieurs couleurs, chacune faisant un petit travail. Les pièces qui semblent conçues ont un seul geste fort — un mur profond dans une petite pièce, un îlot de cuisine saturé, un grand tapis coloré, et laissent tout le reste retomber doucement autour. Décidez où vous voulez que l’œil se pose, et mettez la couleur la plus franche là, et nulle part ailleurs."},
            {"t": "h2", "c": "Un test pratique"},
            {"t": "p", "c": "Échantillonnez sur le mur, dans la pièce réelle, et observez à trois moments de la journée. Des pots d’échantillon bon marché et une semaine de patience évitent le coût d’une repeinte complète. Et quand vous aurez réduit le choix à deux palettes, choisissez celle qui semble la plus calme — la couleur est toujours plus facile à ajouter qu’à soustraire."},
        ],
    },
    {
        "slug": "what-the-design-process-looks-like",
        "date": "2026-04-20",
        "category": "Processus",
        "read_time": 5,
        "image": "blog-5.jpg",
        "title": "À quoi ressemble le processus de design, étape par étape",
        "excerpt": "Du premier appel à la révélation finale. un parcours honnête, en langage simple, de ce qu’est réellement un projet résidentiel.",
        "meta": "Le processus de décoration d’intérieur, étape par étape : découverte, conception, développement, livraison. Ce que le client peut attendre à chaque phase.",
        "blocks": [
            {"t": "p", "c": "Les clients me disent que la partie la plus effrayante d’un projet, c’est l’inconnu : combien de temps cela prendra, qui fait quoi, et où passe l’argent. Voici le processus que j’utilise, en langage simple, pour que vous sachiez à quoi vous attendre."},
            {"t": "h2", "c": "1. Découverte"},
            {"t": "p", "c": "Nous parlons de votre façon de vivre, de travailler et de recevoir — les routines, les habitudes, ce qui vous agace dans l’espace aujourd’hui. J’écoute le sentiment que vous voulez que la pièce porte. Cette étape ne vous coûte qu’une heure, et elle me dit si nous sommes faits pour travailler ensemble."},
            {"t": "h2", "c": "2. Conception"},
            {"t": "p", "c": "Concept, atmosphère, matières et agencement — développés ensemble et affinés jusqu’à ce que le résultat semble inévitable. Vous verrez des plans, des palettes et des échantillons de matières, et nous ferons des allers-retours jusqu’à ce que le design épouse votre façon de vivre réelle. C’est ici que la vision prend forme, avant qu’un seul mur ne soit touché."},
            {"t": "h2", "c": "3. Développement"},
            {"t": "p", "c": "Plans techniques, approvisionnement et coordination avec les artisans et les entreprises, gérés de bout en bout. Vous recevez des budgets clairs et un calendrier réaliste, et je m’occupe des fournisseurs pour que vous ne soyez pas l’intermédiaire. Les inconnues se règlent ici, sur papier, là où elles sont peu coûteuses."},
            {"t": "quote", "c": "Un bon processus reporte les problèmes sur le papier tôt, là où ils sont simples à résoudre — et non sur le chantier, là où ils sont coûteux."},
            {"t": "h2", "c": "4. Livraison"},
            {"t": "p", "c": "Installation et mise en scène, jusqu’au dernier objet. L’espace est remis prêt à vivre — non pas composé pour une photographie, mais agencé pour votre semaine. C’est le moment où tout s’ajuste discrètement, et c’est la raison d’être du processus."},
            {"t": "h2", "c": "Ce qu’il faut demander à tout designer avant de commencer"},
            {"t": "ul", "c": [
                "Comment gérez-vous le budget — et que se passe-t-il s’il évolue ?",
                "Qui gère les fournisseurs, les artisans et les délais ?",
                "Que faites-vous lorsqu’un produit choisi est arrêté ?",
                "Comment communiquerons-nous, et à quelle fréquence ?",
                "Que couvre vos honoraires, et qu’est-ce qui en est exclu ?",
            ]},
            {"t": "p", "c": "Le bon processus est celui qui vous tient informé sans vous noyer dans le détail. Vous devez toujours savoir à quelle étape en est le projet, ce qui vient ensuite, et ce que cela coûte."},
        ],
    },
    {
        "slug": "seven-common-interior-design-mistakes",
        "date": "2026-03-30",
        "category": "Notions de base",
        "read_time": 6,
        "image": "blog-6.jpg",
        "title": "Sept erreurs de décoration courantes (et comment les éviter)",
        "excerpt": "Les erreurs qui vieillissent discrètement une pièce ne relèvent pas du goût. mais de la séquence et de l’échelle. Une check-list pratique avant de rénover.",
        "meta": "Les erreurs de décoration les plus courantes à éviter : éclairage, échelle, couleur, rangements et ordre des travaux. Une check-list pratique pour la rénovation.",
        "blocks": [
            {"t": "p", "c": "Après assez de projets, on commence à voir les mêmes sept erreurs se répéter — non pas dans de mauvaises maisons, mais dans des maisons soignées et bien intentionnées. Aucune ne relève du goût. Elles relèvent de la séquence, de l’échelle, et de l’endroit où va l’attention."},
            {"t": "h2", "c": "1. Planifier la décoration avant l’agencement"},
            {"t": "p", "c": "Choisir un canapé avant de décider comment circule la pièce, c’est acheter des vêtements avant de savoir où l’on va. Commencez par la façon dont l’espace est utilisé et dont les gens le traversent ; les pièces viennent après."},
            {"t": "h2", "c": "2. Tout acheter dans le même showroom"},
            {"t": "p", "c": "Un salon assorti est confortable et oubliable. Les pièces qui ont de la personnalité naissent de pièces aux histoires différentes — une chaise vintage à côté d’un canapé contemporain, une table faite main sous une lampe de grande diffusion. Si tout s’assortit, rien n’a d’importance."},
            {"t": "h2", "c": "3. Accrocher les œuvres trop haut"},
            {"t": "p", "c": "Le centre d’un tableau doit se situer à hauteur des yeux, debout — environ 145 à 150 cm du sol. Au-dessus des canapés, le bord inférieur doit passer à 15 à 20 cm au-dessus du dossier. Une œuvre flotte lorsqu’elle est accrochée comme une plaque de musée."},
            {"t": "h2", "c": "4. Lutter contre la lumière au lieu de l’utiliser"},
            {"t": "p", "c": "Choisir des murs sombres et mélancoliques pour une pièce exposée au nord, ou un seul plafonnier sans variateur, ce sont deux façons de perdre la bataille contre la condition naturelle de la pièce. Concevez avec la lumière dont vous disposez avant d’en ajouter."},
            {"t": "h2", "c": "5. Tout réduire en taille"},
            {"t": "p", "c": "Un mobilier trop petit rend une pièce plus petite et plus vide. Achetez à la bonne échelle pour l’espace, et laissez une pièce être généreuse."},
            {"t": "h2", "c": "6. Décorer le plan, pas la pièce"},
            {"t": "p", "c": "Les plans mentent. Le vrai caractère d’une pièce vient de ce qu’elle ressent en trois dimensions — la profondeur d’un couloir, la hauteur d’un plafond, le trajet du soleil sur le sol. Passez autant de temps à vous imaginer dans la pièce qu’à la disposer sur le papier."},
            {"t": "h2", "c": "7. Ajouter avant d’éditer"},
            {"t": "p", "c": "Quand une pièce ne semble pas juste, l’instinct est d’ajouter un objet de plus. C’est généralement le mauvais instinct. Retirez d’abord — une couche d’objets, un tapis chargé, une lampe en double, et voyez ce que la pièce cherchait à être. La plupart des pièces s’améliorent davantage par la soustraction que par l’addition."},
            {"t": "quote", "c": "Le moyen le plus rapide d’embellir une pièce, c’est d’en retirer quelque chose."},
        ],
    },
]
