# -*- coding: utf-8 -*-
"""Blog posts — ENGLISH. 7 articles, SEO-aligned to the interior design niche."""

BLOG = [
    {
        "slug": "whats-new-in-interiors",
        "date": "2026-08-01",
        "category": "Trends",
        "read_time": 6,
        "image": "blog-4.jpg",
        "title": "What’s New in Interiors Right Now",
        "excerpt": "Warm neutrals, sculptural light, and furniture that earns its place — a short field guide to the direction interiors are moving this season.",
        "meta": "Interior design trends to watch: warm neutrals, sculptural lighting, human-scaled furniture and the return of craft. Notes from Bruno Vinícius.",
        "blocks": [
            {"t": "p", "c": "Trends are useful only if they help you make a decision. Everything below is a direction, not a rule — take what supports the way you actually live and leave the rest."},
            {"t": "h2", "c": "Warm neutrals are back, and they’re not beige"},
            {"t": "p", "c": "The cool greys that dominated interiors for a decade are giving way to warmer, deeper neutrals — think stone, sand, mushroom, olive. The difference matters: warm neutrals carry more light and photograph better, and they make people look good in a room."},
            {"t": "p", "c": "The way to use them without flatness is contrast in texture, not contrast in colour. A sand-coloured wall becomes rich when it meets a linen sofa, a travertine table, and a dark walnut floor."},
            {"t": "h2", "c": "Lighting has become the hero piece"},
            {"t": "p", "c": "Pendant lamps are no longer accessories. Sculptural, sculptural glass and hand-blown fixtures are taking the role the chandelier once had — the first thing you notice in a room. The pattern is the same as the great lighting houses have practised for decades: light as the primary material, everything else arranged around it."},
            {"t": "quote", "c": "Light is the first material I choose. Everything else — colour, furniture, layout — is negotiated around it."},
            {"t": "h2", "c": "Furniture that earns its place"},
            {"t": "p", "c": "The other clear signal is a move away from sets. Matching three-piece suites are disappearing in favour of individual, well-chosen pieces that can move with you — a single sculptural chair, a table you could inherit, a lamp you’ll keep for twenty years."},
            {"t": "h2", "c": "How to follow what’s new without losing yourself"},
            {"t": "p", "c": "There are two useful places to watch new products before they reach stores. The first is independent makers and workshops, who tend to release small runs of honest objects. The second is crowdfunding platforms, where independent designers launch furniture, lighting, and accessories directly — often a season ahead of retail, and usually with the story of the design still attached."},
            {"t": "p", "c": "Neither replaces a showroom visit. But both are excellent for spotting the small, specific ideas — a new table leg, a new way of folding light — that make a room feel current without looking like a catalogue."},
            {"t": "h2", "c": "The short version"},
            {"t": "ul", "c": [
                "Choose warm, deep neutrals and add richness with texture, not colour.",
                "Give one fixture the role of hero — spend the money there.",
                "Buy individual pieces with a story, not matching sets.",
                "Watch makers and independent launches for ideas that arrive early.",
            ]},
            {"t": "p", "c": "Trends come and go. If you design a room that supports your habits and makes you feel at ease, it will look right this season and in ten seasons."},
        ],
    },
    {
        "slug": "how-to-choose-an-interior-design-style",
        "date": "2026-07-14",
        "category": "Fundamentals",
        "read_time": 6,
        "image": "blog-5.jpg",
        "title": "How to Choose an Interior Design Style That Fits Your Life",
        "excerpt": "Most style quizzes miss the point. The right direction comes from how you live, not from Pinterest. A practical way to find yours.",
        "meta": "How to choose an interior design style: a practical process based on how you live, work and host — instead of Pinterest or style quizzes.",
        "blocks": [
            {"t": "p", "c": "Clients often arrive with a dozen saved images and a phrase they’ve borrowed from a magazine: “Scandinavian”, “modern organic”, “quiet luxury”. None of those are wrong. They’re just starting points, and most of them describe the same underlying impulse: a space that feels calm and honest."},
            {"t": "h2", "c": "Start with behaviour, not vocabulary"},
            {"t": "p", "c": "Before thinking about materials or colours, answer three questions honestly. How do you actually use the room, hour by hour? Who is in it with you, and how often? And how do you want to feel when you walk in — rested, energised, welcomed, focused? The style is the answer to those questions, expressed in physical form. Everything else is decoration."},
            {"t": "h2", "c": "Separate what you love from what you want to live with"},
            {"t": "p", "c": "This is the distinction that saves projects. A hotel lobby can be stunning and still be the wrong model for your living room, because a hotel is designed for a thirty-minute stay. Your home is designed for a decade of ordinary evenings. Collect images you love, then split them into two lists: inspiring, and actually liveable. The overlap is your style."},
            {"t": "quote", "c": "A style that asks you to change how you live will not survive contact with your life."},
            {"t": "h2", "c": "Work with one strong reference"},
            {"t": "p", "c": "Out of the overlap, choose one direction as the anchor — the palette or the key piece you feel sure about — and let everything else be negotiated around it. Rooms that feel indecisive usually have two or three strong references pulling against each other. One anchor, applied consistently, is what makes a room feel designed rather than decorated."},
            {"t": "h2", "c": "A quick checklist"},
            {"t": "ul", "c": [
                "Write down how the room is used across a normal week.",
                "Keep a folder of images; split it into ‘inspiring’ and ‘liveable’.",
                "Choose one anchor — a palette, a material, or one piece.",
                "Test the anchor against your daily habits, not against a photo.",
                "Give yourself permission to borrow one detail you simply like.",
            ]},
            {"t": "p", "c": "When in doubt, favour simplicity over trend. It is easier to add personality to a calm base than to subtract it from a busy one — and the calm base is where most people end up wanting to live."},
        ],
    },
    {
        "slug": "the-quiet-power-of-lighting",
        "date": "2026-06-28",
        "category": "Lighting",
        "read_time": 7,
        "image": "blog-3.jpg",
        "title": "The Quiet Power of Lighting: A Designer’s Guide",
        "excerpt": "Lighting decides how a room feels, not how it looks. Three layers, five mistakes, and how to get it right in your own home.",
        "meta": "Interior lighting guide: the three layers of light, common lighting mistakes, and how to design lighting that changes a room's mood.",
        "blocks": [
            {"t": "p", "c": "People remember the furniture and forget the light. But it is the light that makes a room feel generous at seven in the evening and calm at eleven. Most interiors are designed for what they look like in photographs; the ones that feel right are designed around how they behave at different hours."},
            {"t": "h2", "c": "The three layers"},
            {"t": "p", "c": "Good lighting is rarely one fixture. It is three layers working together, each doing a different job:"},
            {"t": "ul", "c": [
                "Ambient — soft, even light that fills the room without glare. Recessed or indirect light, dimmed, at around 2,700K.",
                "Task — focused light where you read, cook, or work. A good reading lamp or an under-cabinet strip does more than you expect.",
                "Accent — the light that draws the eye: a picture light, a wall-washer, a fixture that glows rather than floods.",
            ]},
            {"t": "h2", "c": "The switch you will actually use"},
            {"t": "p", "c": "The single most effective upgrade in any room is a dimmer on the ambient circuit. It is cheap, and it quietly doubles the number of moods a room can hold. Bright for mornings and tasks, low for evenings, somewhere in between for hosting. Rooms with only one lighting level tend to feel either clinical or dark."},
            {"t": "quote", "c": "A room is a different place at six in the morning and at ten at night. Its lighting should be able to change its mind."},
            {"t": "h2", "c": "Five mistakes that age a room"},
            {"t": "ul", "c": [
                "A single overhead light with no dimmer — the fastest way to make a room feel like a waiting room.",
                "Lighting that points down only. Wall and floor light, bounced off surfaces, makes ceilings feel taller and faces kinder.",
                "Cold white in living areas. Save 4,000K+ for utility spaces; keep living rooms warm.",
                "No light at human height. A lamp at eye level when seated changes everything.",
                "Forgetting the lights you see when they are off. A beautiful room with a cheap plastic fixture is a contradiction.",
            ]},
            {"t": "h2", "c": "Where to spend"},
            {"t": "p", "c": "If the budget allows one generous purchase in a room, make it the fixture you see when you walk in — the pendant or wall lamp that carries the accent layer. It is the piece that does the most work and the one people will ask about."},
        ],
    },
    {
        "slug": "small-spaces-big-impact",
        "date": "2026-06-02",
        "category": "Spaces",
        "read_time": 6,
        "image": "blog-1.jpg",
        "title": "Small Spaces, Big Impact: Designing Compact Homes",
        "excerpt": "Small rooms fail from clutter, not from size. Five principles for making a compact space feel generous without moving walls.",
        "meta": "Small space interior design principles: light, scale, storage and one statement piece to make compact homes feel generous.",
        "blocks": [
            {"t": "p", "c": "A small room rarely needs to be bigger. It needs fewer, better-chosen things, and a clearer idea of what the room is for. Almost every compact project I work on improves the moment we remove something rather than add it."},
            {"t": "h2", "c": "One job per room, honestly stated"},
            {"t": "p", "c": "An open-plan kitchen-living room that tries to be a dining room, an office, a cinema and a playroom at once will feel like none of them. Give each zone a single clear job and let the space around it breathe. If a corner has no defined purpose, leave it open — emptiness is a luxury, especially in small homes."},
            {"t": "h2", "c": "Let light do the spatial work"},
            {"t": "p", "c": "Light is the cheapest way to make a room feel larger. Keep windows clear of heavy curtains, use pale wall tones that reflect rather than absorb light, and bounce light off the ceiling and walls instead of lighting only from a single point. A small room that receives soft, indirect light reads as bigger than a large one that is shadowed."},
            {"t": "quote", "c": "In a small space, every decision is a trade. The secret is choosing what to give up."},
            {"t": "h2", "c": "Scale is everything"},
            {"t": "p", "c": "One common mistake is buying furniture that is too small, hoping it will make the room feel bigger. It does the opposite. A compact sofa with proper proportions, a rug that anchors the zone, and one generous piece — a chair, a table, a lamp — give the eye a scale to read the room by. Small everything reads as small."},
            {"t": "h2", "c": "Storage that disappears"},
            {"t": "p", "c": "The visual noise of a small home comes mostly from objects without a home. Built-in storage, painted to match the wall, removes the clutter at the source. Give every category of object a designated place — shoes, coats, papers, cables — and the room itself starts to feel larger."},
            {"t": "h2", "c": "The five principles"},
            {"t": "ul", "c": [
                "Give each zone one clear job; leave one corner empty on purpose.",
                "Maximise natural light and keep wall tones reflective.",
                "Buy furniture at the right scale, and invest in one statement piece.",
                "Hide storage in the architecture rather than adding more furniture.",
                "Edit ruthlessly: everything visible must earn its place.",
            ]},
        ],
    },
    {
        "slug": "color-as-a-tool",
        "date": "2026-05-12",
        "category": "Colour",
        "read_time": 6,
        "image": "blog-2.jpg",
        "title": "Colour as a Tool: Building a Palette That Works",
        "excerpt": "Forget matching the sofa to the rug. Colour works as a system — light, depth, and a single strong move. How to build a palette that holds together.",
        "meta": "How to build an interior color palette: 60-30-10, warm vs cool light, saturation and one strong accent move explained simply.",
        "blocks": [
            {"t": "p", "c": "Most people choose colour the way they choose an outfit they love in a photo — and then wonder why the result doesn’t hold together. Colour in a room works as a system, with a hierarchy, and the system matters more than any single colour."},
            {"t": "h2", "c": "Start with the room’s light, not the trend"},
            {"t": "p", "c": "The same paint reads differently under north-facing light, west sun, and warm bulbs. A north-facing room needs warm tones to feel alive; a sun-drenched room can carry cooler ones. Before sampling colours, notice the light: what direction it comes from, how it changes through the day, and whether the bulbs are warm or cool."},
            {"t": "h2", "c": "The 60-30-10 structure"},
            {"t": "ul", "c": [
                "60% — the dominant tone: walls, floor, and the largest surfaces. Keep it quiet.",
                "30% — the secondary tone: the sofa, the cabinetry, the major furniture. In conversation with the first.",
                "10% — the accent: cushions, a chair, a rug, art. This is where personality lives, and it should stay a minority shareholder.",
            ]},
            {"t": "quote", "c": "A palette is not a collection of favourite colours. It is a set of colours that have agreed to work together."},
            {"t": "h2", "c": "One strong move beats five nice ones"},
            {"t": "p", "c": "Rooms that feel indecisive usually have several colours each doing a small job. Rooms that feel designed have one strong move — a deep wall in a small room, a saturated kitchen island, a generous coloured rug — and let everything else fall quietly around it. Decide where you want the eye to land, and put the boldest colour there and nowhere else."},
            {"t": "h2", "c": "A practical test"},
            {"t": "p", "c": "Sample on the wall, in the actual room, and look at it at three times of day. Cheap sample pots and a week of patience save the cost of a full repaint. And when you have narrowed to two palettes, choose the one that feels calmer — colour is easiest to add later and hardest to subtract."},
        ],
    },
    {
        "slug": "what-the-design-process-looks-like",
        "date": "2026-04-20",
        "category": "Process",
        "read_time": 5,
        "image": "blog-5.jpg",
        "title": "What the Design Process Looks Like, Step by Step",
        "excerpt": "From the first call to the final reveal — an honest, plain-language walk through how a residential project actually runs.",
        "meta": "Interior design process step by step: discovery, concept, development, delivery. What clients can expect at each stage.",
        "blocks": [
            {"t": "p", "c": "Clients tell me the scariest part of a project is the unknown: how long it will take, who does what, and where the money goes. Here is the process I use, in plain language, so you know what to expect."},
            {"t": "h2", "c": "1. Discovery"},
            {"t": "p", "c": "We talk through how you live, work, and host — the routines, the habits, the things that annoy you about the space today. I listen for the feeling you want the room to carry. This stage costs you nothing but an hour, and it tells me whether we’re a good fit."},
            {"t": "h2", "c": "2. Design"},
            {"t": "p", "c": "Concept, mood, materials, and layout — developed together and refined until it feels inevitable. You will see plans, palettes, and material samples, and we will go back and forth until the design matches the way you actually live. This is where the vision takes shape, before a single wall is touched."},
            {"t": "h2", "c": "3. Development"},
            {"t": "p", "c": "Technical drawings, sourcing, and coordination with builders and artisans, managed end to end. You receive clear budgets and a realistic timeline, and I handle the suppliers so you are not the middle person. The unknowns are resolved here, on paper, where they are cheap."},
            {"t": "quote", "c": "A good process moves the problems onto the paper early, where they are cheap to solve — not onto the build, where they are expensive."},
            {"t": "h2", "c": "4. Delivery"},
            {"t": "p", "c": "Installation and styling, down to the last object. The space is handed over ready to live in — not staged for a photograph, but arranged for your week. This is the moment everything quietly clicks, and it is the reason the process exists."},
            {"t": "h2", "c": "What to ask any designer before you start"},
            {"t": "ul", "c": [
                "How do you handle the budget — and what happens if it shifts?",
                "Who manages suppliers, builders, and timelines?",
                "What do you do when a chosen product is discontinued?",
                "How will we communicate, and how often?",
                "What does the fee cover, and what is outside it?",
            ]},
            {"t": "p", "c": "The right process is the one that keeps you informed without burying you in detail. You should always know what stage the project is at, what happens next, and what it costs."},
        ],
    },
    {
        "slug": "seven-common-interior-design-mistakes",
        "date": "2026-03-30",
        "category": "Fundamentals",
        "read_time": 6,
        "image": "blog-6.jpg",
        "title": "Seven Common Interior Design Mistakes (and How to Avoid Them)",
        "excerpt": "The mistakes that quietly age a room aren’t about taste — they’re about sequence and scale. A practical checklist before you renovate.",
        "meta": "Common interior design mistakes to avoid: lighting, scale, colour, storage and sequence. A practical renovation checklist.",
        "blocks": [
            {"t": "p", "c": "After enough projects you start to see the same seven mistakes repeated — not in bad homes, but in careful, well-meaning ones. None of them are about taste. They are about sequence, scale, and where attention goes."},
            {"t": "h2", "c": "1. Planning the decor before the layout"},
            {"t": "p", "c": "Choosing a sofa before deciding how the room flows is like buying clothes before deciding where you’re going. Start with how the space is used and how people move through it; the pieces come after."},
            {"t": "h2", "c": "2. Buying everything from one showroom"},
            {"t": "p", "c": "A matching suite is comfortable and forgettable. Rooms with personality come from pieces with different histories — a vintage chair beside a contemporary sofa, a handmade table under a mass-market lamp. If it all matches, none of it matters."},
            {"t": "h2", "c": "3. Hanging art too high"},
            {"t": "p", "c": "The centre of a picture should sit at eye level when you are standing — roughly 145–150cm from the floor. Above sofas, the bottom edge should clear the back of the sofa by about 15–20cm. Art floats when it hangs like a museum plaque."},
            {"t": "h2", "c": "4. Fighting the light instead of using it"},
            {"t": "p", "c": "Choosing dark, moody walls for a north-facing room, or a single overhead light with no dimmer, are both ways of losing a battle with the room’s natural condition. Design with the light you have before you add more of it."},
            {"t": "h2", "c": "5. Sizing everything down"},
            {"t": "p", "c": "Furniture that is too small makes a room feel smaller and emptier. Buy at the right scale for the space and let one piece be generous."},
            {"t": "h2", "c": "6. Decorating the plan, not the room"},
            {"t": "p", "c": "Plans lie. A room’s true character comes from how it feels in three dimensions — the depth of a corridor, the height of a ceiling, the path of sunlight across the floor. Spend as much time imagining yourself in the room as you do arranging it on paper."},
            {"t": "h2", "c": "7. Adding before editing"},
            {"t": "p", "c": "When a room doesn’t feel right, the instinct is to add another object. It is usually the wrong instinct. Remove first — a layer of objects, a busy rug, a duplicated lamp — and see what the room was trying to be. Most rooms improve more from subtraction than from addition."},
            {"t": "quote", "c": "The fastest way to make a room look better is to take something out of it."},
        ],
    },
]
