# -*- coding: utf-8 -*-
"""Posts do blog — PORTUGUÊS. 7 artigos, alinhados a SEO para o nicho de design de interiores."""

BLOG = [
    {
        "slug": "whats-new-in-interiors",
        "date": "2026-08-01",
        "category": "Tendências",
        "read_time": 6,
        "image": "blog-4.jpg",
        "title": "O Que Há de Novo em Interiores Agora",
        "excerpt": "Neutros quentes, luz escultural e mobiliário que conquista seu lugar. um pequeno guia de campo para a direção que os interiores estão tomando nesta estação.",
        "meta": "Tendências de design de interiores para observar: neutros quentes, iluminação escultural, móveis em escala humana e o retorno do artesanal. Notas de Bruno Vinícius.",
        "blocks": [
            {"t": "p", "c": "Tendências só são úteis se ajudarem você a tomar uma decisão. Tudo abaixo é uma direção, não uma regra — leve o que sustenta o modo como você realmente vive e deixe o resto de lado."},
            {"t": "h2", "c": "Os neutros quentes voltaram — e não são bege"},
            {"t": "p", "c": "Os cinzas frios que dominaram os interiores por uma década estão dando lugar a neutros mais quentes e profundos — pense em pedra, areia, cogumelo, oliva. A diferença importa: os neutros quentes carregam mais luz, fotografam melhor e fazem as pessoas ficarem bem em um ambiente."},
            {"t": "p", "c": "A forma de usá-los sem achatar o espaço é o contraste de textura, não o contraste de cor. Uma parede cor de areia ganha riqueza quando encontra um sofá de linho, uma mesa de travertino e um piso escuro de nogueira."},
            {"t": "h2", "c": "A iluminação virou a peça protagonista"},
            {"t": "p", "c": "As luminárias pendentes deixaram de ser acessórios. Peças esculturais, em vidro soprado e feito à mão, assumem o papel que o lustre um dia teve — a primeira coisa que se nota em um ambiente. O princípio é o mesmo que as grandes casas de iluminação praticam há décadas: a luz como material principal, e tudo o mais organizado em torno dela."},
            {"t": "quote", "c": "A luz é o primeiro material que escolho. Todo o resto — cor, mobiliário, layout — é negociado em torno dela."},
            {"t": "h2", "c": "Mobiliário que conquista seu lugar"},
            {"t": "p", "c": "O outro sinal claro é o afastamento dos conjuntos. Os jogos de três peças combinando estão desaparecendo em favor de peças individuais e bem escolhidas, que podem se mover com você — uma única cadeira escultural, uma mesa que você herdaria, um abajur que ficará com você por vinte anos."},
            {"t": "h2", "c": "Como acompanhar as novidades sem se perder"},
            {"t": "p", "c": "Existem dois bons lugares para observar novos produtos antes de chegarem às lojas. O primeiro são os makers e ateliês independentes, que costumam lançar pequenas tiragens de objetos honestos. O segundo são as plataformas de financiamento coletivo, onde designers independentes lançam mobiliário, iluminação e acessórios diretamente — muitas vezes uma estação à frente do varejo, e quase sempre com a história do projeto ainda anexada."},
            {"t": "p", "c": "Nenhum dos dois substitui a visita a um showroom. Mas ambos são excelentes para perceber as pequenas ideias específicas — um novo pé de mesa, um novo jeito de dobrar a luz, que deixam um ambiente atual sem parecer catálogo."},
            {"t": "h2", "c": "A versão curta"},
            {"t": "ul", "c": [
                "Escolha neutros quentes e profundos e acrescente riqueza com textura, não com cor.",
                "Dê a uma peça o papel de protagonista — é ali que o dinheiro deve ir.",
                "Compre peças individuais com história, não conjuntos combinando.",
                "Acompanhe makers e lançamentos independentes para ideias que chegam cedo.",
            ]},
            {"t": "p", "c": "Tendências vão e vêm. Se você projetar um ambiente que sustenta seus hábitos e faz você se sentir à vontade, ele parecerá certo nesta estação e daqui a dez."},
        ],
    },
    {
        "slug": "how-to-choose-an-interior-design-style",
        "date": "2026-07-14",
        "category": "Fundamentos",
        "read_time": 6,
        "image": "blog-5.jpg",
        "title": "Como escolher um estilo de decoração que cabe na sua vida",
        "excerpt": "A maioria dos testes de estilo erra o ponto. A direção certa vem de como você vive, não do Pinterest. Um caminho prático para encontrar a sua.",
        "meta": "Como escolher um estilo de decoração: um processo prático baseado em como você vive, trabalha e recebe. em vez do Pinterest ou de testes de estilo.",
        "blocks": [
            {"t": "p", "c": "Clientes costumam chegar com uma dúzia de imagens salvas e uma frase emprestada de uma revista: “escandinavo”, “orgânico moderno”, “luxo silencioso”. Nenhuma delas está errada. Elas são apenas pontos de partida, e quase todas descrevem o mesmo impulso de fundo: um espaço que se sente calmo e honesto."},
            {"t": "h2", "c": "Comece pelo comportamento, não pelo vocabulário"},
            {"t": "p", "c": "Antes de pensar em materiais ou cores, responda a três perguntas com honestidade. Como você realmente usa o ambiente, hora a hora? Quem está nele com você, e com que frequência? E como você quer se sentir ao entrar — descansado, energizado, acolhido, concentrado? O estilo é a resposta a essas perguntas, expressa em forma física. Todo o resto é decoração."},
            {"t": "h2", "c": "Separe o que você ama do que você quer viver"},
            {"t": "p", "c": "Essa é a distinção que salva projetos. Um lobby de hotel pode ser deslumbrante e ainda assim ser o modelo errado para a sua sala, porque um hotel é projetado para uma estadia de trinta minutos. Sua casa é projetada para uma década de noites comuns. Colecione as imagens que você ama e depois divida-as em duas listas: inspiradoras e realmente habitáveis. A intersecção é o seu estilo."},
            {"t": "quote", "c": "Um estilo que pede que você mude o modo como vive não sobrevive ao contato com a sua vida."},
            {"t": "h2", "c": "Trabalhe com uma referência forte"},
            {"t": "p", "c": "Da intersecção, escolha uma direção como âncora — a paleta ou a peça-chave sobre a qual você tem certeza, e deixe todo o resto ser negociado em torno dela. Ambientes que parecem indecisos normalmente têm duas ou três referências fortes puxando umas contra as outras. Uma âncora, aplicada com constância, é o que faz um ambiente parecer projetado em vez de decorado."},
            {"t": "h2", "c": "Uma lista rápida"},
            {"t": "ul", "c": [
                "Escreva como o ambiente é usado ao longo de uma semana comum.",
                "Mantenha uma pasta de imagens; divida-a entre ‘inspiradoras’ e ‘habitáveis’.",
                "Escolha uma âncora — uma paleta, um material ou uma única peça.",
                "Teste a âncora contra seus hábitos diários, não contra uma foto.",
                "Permita-se emprestar um detalhe que você simplesmente gosta.",
            ]},
            {"t": "p", "c": "Em caso de dúvida, prefira a simplicidade à tendência. É mais fácil acrescentar personalidade a uma base calma do que subtraí-la de uma base ocupada — e é na base calma que a maioria das pessoas acaba querendo viver."},
        ],
    },
    {
        "slug": "the-quiet-power-of-lighting",
        "date": "2026-06-28",
        "category": "Iluminação",
        "read_time": 7,
        "image": "blog-3.jpg",
        "title": "O Poder Silencioso da Iluminação: Guia de um Designer",
        "excerpt": "É a iluminação que decide como um ambiente se sente, não como ele parece. Três camadas, cinco erros e como acertar na sua própria casa.",
        "meta": "Guia de iluminação de interiores: as três camadas de luz, erros comuns de iluminação e como projetar a luz que muda o clima de um ambiente.",
        "blocks": [
            {"t": "p", "c": "As pessoas lembram do mobiliário e esquecem da luz. Mas é a luz que faz um ambiente parecer generoso às sete da noite e calmo às onze. A maioria dos interiores é projetada para o que parece nas fotografias; os que se sentem certos são projetados em torno de como se comportam em diferentes horas."},
            {"t": "h2", "c": "As três camadas"},
            {"t": "p", "c": "Uma boa iluminação raramente é uma única luminária. São três camadas trabalhando juntas, cada uma com um papel diferente:"},
            {"t": "ul", "c": [
                "Ambiental — luz suave e uniforme que preenche o ambiente sem ofuscar. Luz embutida ou indireta, dimerizada, em torno de 2.700K.",
                "Tarefa: luz focada onde você lê, cozinha ou trabalha. Um bom abajur de leitura ou uma fita sob o armário rende mais do que você imagina.",
                "Destaque: a luz que atrai o olhar: um quadro iluminado, um wall-washer, uma peça que brilha em vez de inundar.",
            ]},
            {"t": "h2", "c": "O interruptor que você vai usar de verdade"},
            {"t": "p", "c": "O upgrade mais eficaz em qualquer ambiente é um dimmer no circuito da luz ambiente. É barato e, silenciosamente, dobra o número de climas que um ambiente pode abrigar. Forte para as manhãs e as tarefas, baixa para as noites, em algum ponto intermediário para receber. Ambientes com apenas um nível de luz tendem a parecer clínicos ou escuros."},
            {"t": "quote", "c": "Um ambiente é um lugar diferente às seis da manhã e às dez da noite. Sua iluminação deve ser capaz de mudar de ideia."},
            {"t": "h2", "c": "Cinco erros que envelhecem um ambiente"},
            {"t": "ul", "c": [
                "Uma única luz central sem dimmer — o caminho mais rápido para fazer um ambiente parecer uma sala de espera.",
                "Iluminação que aponta só para baixo. A luz de parede e de piso, refletida nas superfícies, faz os tetos parecerem mais altos e os rostos, mais gentis.",
                "Branco frio nas áreas de convivência. Guarde 4.000K+ para espaços utilitários; mantenha as salas quentes.",
                "Sem luz na altura humana. Um abajur na altura dos olhos, sentado, muda tudo.",
                "Esquecer das luzes que você vê quando estão apagadas. Um ambiente bonito com uma peça plástica barata é uma contradição.",
            ]},
            {"t": "h2", "c": "Onde investir"},
            {"t": "p", "c": "Se o orçamento permitir uma única compra generosa em um ambiente, faça dela a peça que você vê ao entrar — a pendente ou a arandela que carrega a camada de destaque. É a peça que faz o trabalho mais pesado e a que as pessoas vão perguntar sobre."},
        ],
    },
    {
        "slug": "small-spaces-big-impact",
        "date": "2026-06-02",
        "category": "Espaços",
        "read_time": 6,
        "image": "blog-1.jpg",
        "title": "Espaços Pequenos, Grande Impacto: Projetando Casas Compactas",
        "excerpt": "Ambientes pequenos falham pelo excesso, não pelo tamanho. Cinco princípios para fazer um espaço compacto parecer generoso sem mover paredes.",
        "meta": "Princípios de design de interiores para espaços pequenos: luz, escala, armazenamento e uma peça de destaque para fazer casas compactas parecerem generosas.",
        "blocks": [
            {"t": "p", "c": "Um ambiente pequeno raramente precisa ser maior. Precisa de menos coisas, melhor escolhidas, e de uma ideia mais clara sobre para que serve. Quase todo projeto compacto em que trabalho melhora no momento em que removemos algo em vez de acrescentar."},
            {"t": "h2", "c": "Uma função por ambiente, declarada com honestidade"},
            {"t": "p", "c": "Uma cozinha americana que tenta ser, ao mesmo tempo, sala de jantar, escritório, cinema e brinquedoteca não parecerá nenhuma delas. Dê a cada zona uma única função clara e deixe o espaço ao redor respirar. Se um canto não tem propósito definido, deixe-o vazio — o vazio é um luxo, especialmente em casas pequenas."},
            {"t": "h2", "c": "Deixe a luz fazer o trabalho espacial"},
            {"t": "p", "c": "A luz é o jeito mais barato de fazer um ambiente parecer maior. Mantenha as janelas livres de cortinas pesadas, use tons claros que refletem em vez de absorver a luz, e faça a luz quicar no teto e nas paredes em vez de iluminar apenas de um único ponto. Um ambiente pequeno que recebe luz suave e indireta parece maior do que um grande tomado por sombras."},
            {"t": "quote", "c": "Em um espaço pequeno, toda decisão é uma troca. O segredo é escolher o que você abre mão."},
            {"t": "h2", "c": "Escala é tudo"},
            {"t": "p", "c": "Um erro comum é comprar móveis pequenos demais, na esperança de que o ambiente pareça maior. O efeito é o oposto. Um sofá compacto com proporções corretas, um tapete que ancora a zona e uma peça generosa — uma cadeira, uma mesa, uma luminária, dão ao olhar uma escala para ler o ambiente. Tudo pequeno lê como pequeno."},
            {"t": "h2", "c": "Armazenamento que desaparece"},
            {"t": "p", "c": "O ruído visual de uma casa pequena vem, em sua maior parte, dos objetos sem casa. Armários embutidos, pintados na cor da parede, removem a desordem na origem. Dê a cada categoria de objeto um lugar designado — sapatos, casacos, papéis, cabos, e o próprio ambiente começa a parecer maior."},
            {"t": "h2", "c": "Os cinco princípios"},
            {"t": "ul", "c": [
                "Dê a cada zona uma função clara; deixe um canto vazio de propósito.",
                "Maximize a luz natural e mantenha tons de parede reflexivos.",
                "Compre móveis na escala certa e invista em uma peça de destaque.",
                "Esconda o armazenamento na arquitetura, em vez de acrescentar mais móveis.",
                "Edite com rigor: tudo o que fica visível precisa conquistar seu lugar.",
            ]},
        ],
    },
    {
        "slug": "color-as-a-tool",
        "date": "2026-05-12",
        "category": "Cor",
        "read_time": 6,
        "image": "blog-2.jpg",
        "title": "A Cor como Ferramenta: Construindo uma Paleta que Funciona",
        "excerpt": "Esqueça combinar o sofá com o tapete. A cor funciona como um sistema. luz, profundidade e um único movimento forte. Como construir uma paleta que se sustenta.",
        "meta": "Como construir uma paleta de cores de interiores: 60-30-10, luz quente vs fria, saturação e um único acento forte, explicados de forma simples.",
        "blocks": [
            {"t": "p", "c": "A maioria das pessoas escolhe cor do mesmo jeito que escolhe uma roupa que amou em uma foto — e depois se pergunta por que o resultado não se sustenta. A cor em um ambiente funciona como um sistema, com uma hierarquia, e o sistema importa mais do que qualquer cor isolada."},
            {"t": "h2", "c": "Comece pela luz do ambiente, não pela tendência"},
            {"t": "p", "c": "A mesma tinta se lê de formas diferentes sob a luz de uma janela voltada para o norte, sob o sol do oeste e sob lâmpadas quentes. Um ambiente voltado para o norte precisa de tons quentes para se sentir vivo; um ambiente banhado de sol pode carregar os mais frios. Antes de testar cores, observe a luz: de que direção ela vem, como muda ao longo do dia e se as lâmpadas são quentes ou frias."},
            {"t": "h2", "c": "A estrutura 60-30-10"},
            {"t": "ul", "c": [
                "60%: o tom dominante: paredes, piso e as maiores superfícies. Mantenha-o tranquilo.",
                "30%: o tom secundário: o sofá, os armários, o mobiliário principal. Em diálogo com o primeiro.",
                "10%: o acento: almofadas, uma cadeira, um tapete, arte. É onde a personalidade mora, e deve continuar sendo sócio minoritário.",
            ]},
            {"t": "quote", "c": "Uma paleta não é uma coleção de cores favoritas. É um conjunto de cores que concordaram em trabalhar juntas."},
            {"t": "h2", "c": "Um movimento forte vence cinco bonitos"},
            {"t": "p", "c": "Ambientes que parecem indecisos normalmente têm várias cores, cada uma fazendo um pequeno trabalho. Ambientes que parecem projetados têm um único movimento forte — uma parede escura em um cômodo pequeno, uma ilha de cozinha saturada, um tapete colorido generoso, e deixam todo o resto cair silenciosamente ao redor. Decida onde você quer que o olhar descanse e coloque a cor mais ousada ali, e em nenhum outro lugar."},
            {"t": "h2", "c": "Um teste prático"},
            {"t": "p", "c": "Teste na parede, no próprio ambiente, e observe em três momentos do dia. Latas de amostra baratas e uma semana de paciência economizam o custo de uma repintura completa. E quando você reduzir a duas paletas, escolha a que se sente mais calma — a cor é a mais fácil de adicionar depois e a mais difícil de subtrair."},
        ],
    },
    {
        "slug": "what-the-design-process-looks-like",
        "date": "2026-04-20",
        "category": "Processo",
        "read_time": 5,
        "image": "blog-5.jpg",
        "title": "Como É o Processo de Design, Passo a Passo",
        "excerpt": "Da primeira conversa à entrega final. um percurso honesto e em linguagem clara sobre como um projeto residencial realmente acontece.",
        "meta": "Processo de design de interiores passo a passo: descoberta, conceito, desenvolvimento, entrega. O que esperar de cada etapa do projeto.",
        "blocks": [
            {"t": "p", "c": "Clientes me dizem que a parte mais assustadora de um projeto é o desconhecido: quanto tempo vai levar, quem faz o quê e para onde vai o dinheiro. Aqui está o processo que eu uso, em linguagem clara, para que você saiba o que esperar."},
            {"t": "h2", "c": "1. Descoberta"},
            {"t": "p", "c": "Conversamos sobre como você vive, trabalha e recebe — as rotinas, os hábitos, as coisas que hoje incomodam no espaço. Eu escuto a sensação que você quer que o ambiente carregue. Esta etapa não custa nada além de uma hora, e me diz se somos uma boa combinação."},
            {"t": "h2", "c": "2. Design"},
            {"t": "p", "c": "Conceito, clima, materiais e layout — desenvolvidos juntos e refinados até parecerem inevitáveis. Você verá plantas, paletas e amostras de materiais, e vamos trabalhar em idas e vindas até o projeto combinar com o modo como você realmente vive. É aqui que a visão toma forma, antes que uma única parede seja tocada."},
            {"t": "h2", "c": "3. Desenvolvimento"},
            {"t": "p", "c": "Desenhos técnicos, compras e coordenação com construtores e artesãos, geridos de ponta a ponta. Você recebe orçamentos claros e um cronograma realista, e eu cuido dos fornecedores para que você não seja o intermediário. As incógnitas são resolvidas aqui, no papel, onde são baratas."},
            {"t": "quote", "c": "Um bom processo transfere os problemas para o papel cedo, onde são baratos de resolver — e não para a obra, onde são caros."},
            {"t": "h2", "c": "4. Entrega"},
            {"t": "p", "c": "Instalação e ambientação, até o último objeto. O espaço é entregue pronto para ser vivido — não montado para uma fotografia, mas arrumado para a sua semana. É o momento em que tudo se encaixa silenciosamente, e é a razão de o processo existir."},
            {"t": "h2", "c": "O que perguntar a qualquer designer antes de começar"},
            {"t": "ul", "c": [
                "Como você lida com o orçamento — e o que acontece se ele mudar?",
                "Quem gerencia fornecedores, construtores e cronogramas?",
                "O que você faz quando um produto escolhido sai de linha?",
                "Como vamos nos comunicar, e com que frequência?",
                "O que o honorário cobre, e o que está fora dele?",
            ]},
            {"t": "p", "c": "O processo certo é o que mantém você informado sem afogá-lo em detalhes. Você deve sempre saber em que etapa o projeto está, o que vem a seguir e quanto custa."},
        ],
    },
    {
        "slug": "seven-common-interior-design-mistakes",
        "date": "2026-03-30",
        "category": "Fundamentos",
        "read_time": 6,
        "image": "blog-6.jpg",
        "title": "Sete Erros Comuns de Decoração (e Como Evitá-los)",
        "excerpt": "Os erros que envelhecem um ambiente silenciosamente não são questão de gosto. são de sequência e escala. Uma lista prática antes de reformar.",
        "meta": "Erros comuns de decoração para evitar: iluminação, escala, cor, armazenamento e sequência. Uma lista prática para a sua reforma.",
        "blocks": [
            {"t": "p", "c": "Depois de projetos suficientes, você começa a ver os mesmos sete erros se repetindo — não em casas ruins, mas em casas cuidadosas e bem-intencionadas. Nenhum deles é questão de gosto. São questões de sequência, de escala e de para onde a atenção vai."},
            {"t": "h2", "c": "1. Planejar a decoração antes do layout"},
            {"t": "p", "c": "Escolher um sofá antes de decidir como o ambiente flui é como comprar roupa antes de decidir para onde você vai. Comece por como o espaço é usado e como as pessoas se movem por ele; as peças vêm depois."},
            {"t": "h2", "c": "2. Comprar tudo de um único showroom"},
            {"t": "p", "c": "Um conjunto combinando é confortável e esquecível. Ambientes com personalidade vêm de peças com histórias diferentes — uma cadeira vintage ao lado de um sofá contemporâneo, uma mesa artesanal sob um abajur de mercado. Se tudo combina, nada importa."},
            {"t": "h2", "c": "3. Pendurar quadros altos demais"},
            {"t": "p", "c": "O centro de um quadro deve ficar na altura dos olhos quando você está de pé — cerca de 145–150cm do piso. Acima de sofás, a borda inferior deve passar cerca de 15–20cm do encosto. A arte flutua quando pendurada como uma plaqueta de museu."},
            {"t": "h2", "c": "4. Brigar com a luz em vez de usá-la"},
            {"t": "p", "c": "Escolher paredes escuras e sombrias para um ambiente voltado para o norte, ou uma única luz central sem dimmer, são duas formas de perder a batalha contra a condição natural do espaço. Projete com a luz que você tem antes de acrescentar mais."},
            {"t": "h2", "c": "5. Diminuir tudo"},
            {"t": "p", "c": "Móveis pequenos demais fazem o ambiente parecer menor e mais vazio. Compre na escala certa para o espaço e deixe uma peça ser generosa."},
            {"t": "h2", "c": "6. Decorar a planta, não o ambiente"},
            {"t": "p", "c": "Plantas mentem. O caráter verdadeiro de um ambiente vem de como ele se sente em três dimensões — a profundidade de um corredor, a altura de um teto, o caminho da luz do sol pelo piso. Gaste tanto tempo se imaginando dentro do ambiente quanto gasto organizando-o no papel."},
            {"t": "h2", "c": "7. Acrescentar antes de editar"},
            {"t": "p", "c": "Quando um ambiente não se sente certo, o instinto é acrescentar mais um objeto. Geralmente é o instinto errado. Remova primeiro — uma camada de objetos, um tapete agitado, um abajur duplicado, e veja o que o ambiente tentava ser. A maioria dos ambientes melhora mais pela subtração do que pela adição."},
            {"t": "quote", "c": "O jeito mais rápido de fazer um ambiente parecer melhor é tirar algo dele."},
        ],
    },
]
