# -*- coding: utf-8 -*-
"""Artículos de blog — ESPAÑOL. 7 artículos, alineados con SEO para el nicho de interiorismo."""

BLOG = [
    {
        "slug": "whats-new-in-interiors",
        "date": "2026-08-01",
        "category": "Tendencias",
        "read_time": 6,
        "image": "blog-4.jpg",
        "title": "Lo nuevo en interiores, ahora mismo",
        "excerpt": "Neutros cálidos, luz escultórica y muebles que se ganan su lugar: una breve guía de campo sobre hacia dónde se mueve el interiorismo esta temporada.",
        "meta": "Tendencias de interiorismo que observar: neutros cálidos, iluminación escultórica, mobiliario a escala humana y el regreso de la artesanía. Notas de Bruno Vinícius.",
        "blocks": [
            {"t": "p", "c": "Las tendencias solo son útiles si te ayudan a tomar una decisión. Todo lo que sigue es una dirección, no una regla: toma aquello que apoye la forma en que realmente vives y deja el resto."},
            {"t": "h2", "c": "Los neutros cálidos han vuelto, y no son beige"},
            {"t": "p", "c": "Los grises fríos que dominaron los interiores durante una década están dejando paso a neutros más cálidos y profundos: piensa en piedra, arena, seta, oliva. La diferencia importa: los neutros cálidos captan más luz, se ven mejor en fotografía y favorecen a las personas dentro de la estancia."},
            {"t": "p", "c": "La forma de usarlos sin que el resultado sea plano está en el contraste de texturas, no de color. Una pared en tono arena se enriquece cuando se encuentra con un sofá de lino, una mesa de travertino y un suelo de nogal oscuro."},
            {"t": "h2", "c": "La iluminación se ha convertido en la pieza protagonista"},
            {"t": "p", "c": "Las lámparas colgantes ya no son un accesorio. El vidrio escultural y las piezas sopladas a mano están ocupando el papel que antaño tenía la lámpara de araña: lo primero que se advierte al entrar en una estancia. El patrón es el mismo que las grandes casas de iluminación practican desde hace décadas: la luz como material principal y todo lo demás dispuesto a su alrededor."},
            {"t": "quote", "c": "La luz es el primer material que elijo. Todo lo demás —el color, el mobiliario, la distribución— se negocia en torno a ella."},
            {"t": "h2", "c": "Muebles que se ganan su lugar"},
            {"t": "p", "c": "La otra señal clara es el alejamiento de los conjuntos. Los juegos de tres piezas a juego están desapareciendo en favor de piezas individuales y bien elegidas que pueden acompañarte a donde vayas: una única silla escultórica, una mesa que quieras heredar, una lámpara que conservarás durante veinte años."},
            {"t": "h2", "c": "Cómo seguir lo nuevo sin perderte a ti mismo"},
            {"t": "p", "c": "Hay dos lugares útiles donde ver productos nuevos antes de que lleguen a las tiendas. El primero son los artesanos y talleres independientes, que suelen lanzar pequeñas tiradas de objetos honestos. El segundo son las plataformas de financiación colectiva, donde diseñadores independientes presentan mobiliario, iluminación y accesorios directamente —a menudo con una temporada de ventaja sobre el comercio minorista y, por lo general, con la historia del diseño todavía intacta."},
            {"t": "p", "c": "Ninguna de las dos sustituye a una visita al showroom. Pero ambas son excelentes para detectar esas pequeñas y concretas ideas —una nueva pata de mesa, una nueva forma de plegar la luz, que hacen que una estancia se sienta actual sin parecer un catálogo."},
            {"t": "h2", "c": "La versión breve"},
            {"t": "ul", "c": [
                "Elige neutros cálidos y profundos y añade riqueza con textura, no con color.",
                "Da a una sola pieza el papel protagonista: invierte ahí el dinero.",
                "Compra piezas individuales con historia, no conjuntos a juego.",
                "Observa a los artesanos y los lanzamientos independientes para captar ideas antes que nadie.",
            ]},
            {"t": "p", "c": "Las tendencias van y vienen. Si diseñas una estancia que sostiene tus hábitos y te hace sentir en calma, se verá bien esta temporada y dentro de diez."},
        ],
    },
    {
        "slug": "how-to-choose-an-interior-design-style",
        "date": "2026-07-14",
        "category": "Fundamentos",
        "read_time": 6,
        "image": "blog-5.jpg",
        "title": "Cómo elegir un estilo de interiorismo que encaje con tu vida",
        "excerpt": "La mayoría de los test de estilo pasan por alto lo esencial. La dirección correcta nace de cómo vives, no de Pinterest. Una forma práctica de encontrar la tuya.",
        "meta": "Cómo elegir un estilo de interiorismo: un proceso práctico basado en cómo vives, trabajas y recibes. en lugar de Pinterest o los test de estilo.",
        "blocks": [
            {"t": "p", "c": "Los clientes suelen llegar con una docena de imágenes guardadas y una frase prestada de una revista: «escandinavo», «orgánico moderno», «lujo silencioso». Ninguna de ellas es un error. Son solo puntos de partida, y la mayoría describen el mismo impulso de fondo: un espacio que se sienta sereno y honesto."},
            {"t": "h2", "c": "Empieza por el comportamiento, no por el vocabulario"},
            {"t": "p", "c": "Antes de pensar en materiales o colores, responde con sinceridad a tres preguntas. ¿Cómo usas la estancia en realidad, hora a hora? ¿Quién la comparte contigo, y con qué frecuencia? ¿Y cómo quieres sentirte al entrar —descansado, con energía, acogido, concentrado? El estilo es la respuesta a esas preguntas, expresada en forma física. Todo lo demás es decoración."},
            {"t": "h2", "c": "Separa lo que amas de aquello con lo que quieres vivir"},
            {"t": "p", "c": "Esta es la distinción que importa. El vestíbulo de un hotel puede ser impresionante y aun así ser un mal modelo para tu salón, porque un hotel está pensado para una estancia de treinta minutos. Tu casa está pensada para una década de noches corrientes. Reúne las imágenes que amas y divídelas en dos listas: inspiradoras y realmente habitables. La intersección es tu estilo."},
            {"t": "quote", "c": "Un estilo que te pide cambiar tu forma de vivir no sobrevivirá al contacto con tu vida."},
            {"t": "h2", "c": "Trabaja con una única referencia fuerte"},
            {"t": "p", "c": "De la intersección, elige una dirección como ancla —la paleta o la pieza clave de la que te sientes seguro, y deja que todo lo demás se negocie en torno a ella. Las estancias que se perciben indecisas suelen tener dos o tres referencias fuertes tirando en direcciones opuestas. Una sola ancla, aplicada con constancia, es lo que hace que un espacio parezca diseñado y no decorado."},
            {"t": "h2", "c": "Una lista rápida"},
            {"t": "ul", "c": [
                "Anota cómo se usa la estancia a lo largo de una semana normal.",
                "Mantén una carpeta de imágenes; divídela entre «inspiradoras» y «habitables».",
                "Elige una ancla: una paleta, un material o una sola pieza.",
                "Prueba la ancla contra tus hábitos diarios, no contra una fotografía.",
                "Permítete tomar prestado un detalle que simplemente te guste.",
            ]},
            {"t": "p", "c": "Ante la duda, elige la sencillez antes que la tendencia. Es más fácil añadir personalidad a una base serena que restarla de una atrevida —y la base serena es donde la mayoría acaba queriendo vivir."},
        ],
    },
    {
        "slug": "the-quiet-power-of-lighting",
        "date": "2026-06-28",
        "category": "Iluminación",
        "read_time": 7,
        "image": "blog-3.jpg",
        "title": "El poder silencioso de la iluminación: guía de diseñador",
        "excerpt": "La iluminación decide cómo se siente una estancia, no cómo se ve. Tres capas, cinco errores y cómo acertar en tu propia casa.",
        "meta": "Guía de iluminación interior: las tres capas de luz, los errores más comunes y cómo diseñar una iluminación que cambie el ánimo de la estancia.",
        "blocks": [
            {"t": "p", "c": "La gente recuerda el mobiliario y olvida la luz. Pero es la luz la que hace que una estancia se sienta generosa a las siete de la tarde y serena a las once. La mayoría de los interiores se diseñan pensando en cómo se verán en fotografía; los que se sienten bien están pensados en torno a cómo se comportan a distintas horas."},
            {"t": "h2", "c": "Las tres capas"},
            {"t": "p", "c": "Una buena iluminación rara vez es una sola lámpara. Son tres capas trabajando juntas, cada una con un papel distinto:"},
            {"t": "ul", "c": [
                "Ambiental: luz suave y uniforme que llena la estancia sin deslumbramiento. Luz empotrada o indirecta, regulada, en torno a los 2.700 K.",
                "Tarea: luz focalizada donde lees, cocinas o trabajas. Una buena lámpara de lectura o una banda bajo el armario hace más de lo que imaginas.",
                "Acento: la luz que atrae la mirada: un cuadro iluminado, una luz rasante en la pared, una lámpara que resplandece en lugar de inundar.",
            ]},
            {"t": "h2", "c": "El interruptor que de verdad vas a usar"},
            {"t": "p", "c": "La mejora más eficaz en cualquier estancia es un regulador en el circuito ambiental. Es barato y, en silencio, duplica el número de estados de ánimo que puede albergar un espacio. Brillante para las mañanas y las tareas, baja para las noches, en un punto intermedio para recibir. Las estancias con un único nivel de luz tienden a parecer clínicas u oscuras."},
            {"t": "quote", "c": "Una estancia es un lugar distinto a las seis de la mañana y a las diez de la noche. Su iluminación debería poder cambiar de opinión."},
            {"t": "h2", "c": "Cinco errores que envejecen una estancia"},
            {"t": "ul", "c": [
                "Una única luz de techo sin regulador: la vía más rápida para que un espacio parezca una sala de espera.",
                "Iluminación que solo apunta hacia abajo. La luz de pared y de suelo, rebotada en las superficies, hace que los techos parezcan más altos y los rostros más amables.",
                "Blanco frío en las zonas de estar. Reserva los 4.000 K o más para espacios de servicio; mantén cálidos los salones.",
                "Sin luz a la altura humana. Una lámpara a la altura de los ojos cuando estás sentado lo cambia todo.",
                "Olvidar las luces que se ven apagadas. Una estancia hermosa con una lámpara de plástico barato es una contradicción.",
            ]},
            {"t": "h2", "c": "Dónde invertir"},
            {"t": "p", "c": "Si el presupuesto permite una compra generosa en una estancia, que sea la pieza que ves al entrar —el colgante o la lámpara de pared que sostiene la capa de acento. Es la pieza que más trabajo hace y la que todos te preguntarán."},
        ],
    },
    {
        "slug": "small-spaces-big-impact",
        "date": "2026-06-02",
        "category": "Espacios",
        "read_time": 6,
        "image": "blog-1.jpg",
        "title": "Espacios pequeños, gran impacto: diseñar hogares compactos",
        "excerpt": "Los espacios pequeños fallan por el desorden, no por el tamaño. Cinco principios para hacer que un espacio compacto se sienta generoso sin mover paredes.",
        "meta": "Principios de interiorismo para espacios pequeños: luz, escala, almacenamiento y una pieza protagonista para que los hogares compactos se sientan generosos.",
        "blocks": [
            {"t": "p", "c": "Una estancia pequeña rara vez necesita ser más grande. Necesita menos cosas, mejor elegidas, y una idea más clara de para qué sirve. Casi todos los proyectos compactos en los que trabajo mejoran en el momento en que quitamos algo en lugar de añadirlo."},
            {"t": "h2", "c": "Una función por estancia, declarada con honestidad"},
            {"t": "p", "c": "Una cocina-salón de planta abierta que a la vez intenta ser comedor, oficina, sala de cine y cuarto de juegos no acabará pareciendo ninguna de ellas. Dale a cada zona una única función clara y deja que el espacio a su alrededor respire. Si un rincón no tiene un propósito definido, déjalo libre: el vacío es un lujo, sobre todo en hogares pequeños."},
            {"t": "h2", "c": "Deja que la luz haga el trabajo espacial"},
            {"t": "p", "c": "La luz es la forma más económica de hacer que una estancia parezca más grande. Mantén las ventanas libres de cortinas pesadas, usa tonos de pared pálidos que reflejen la luz en lugar de absorberla, y rebota la luz en el techo y las paredes en lugar de iluminar desde un único punto. Un espacio pequeño que recibe luz suave e indirecta se lee como más grande que uno grande sumido en sombras."},
            {"t": "quote", "c": "En un espacio pequeño, cada decisión es una renuncia. El secreto está en elegir qué entregar a cambio."},
            {"t": "h2", "c": "La escala lo es todo"},
            {"t": "p", "c": "Un error frecuente es comprar muebles demasiado pequeños, con la esperanza de que la estancia parezca más grande. Consigue lo contrario. Un sofá compacto con proporciones correctas, una alfombra que ancle la zona y una pieza generosa —una silla, una mesa, una lámpara, dan al ojo una escala con la que leer la estancia. Si todo es pequeño, todo se lee como pequeño."},
            {"t": "h2", "c": "Almacenamiento que desaparece"},
            {"t": "p", "c": "El ruido visual de un hogar pequeño procede sobre todo de los objetos sin hogar. El almacenamiento empotrado, pintado a juego con la pared, elimina el desorden de raíz. Dale a cada categoría de objeto un lugar asignado —zapatos, abrigos, papeles, cables, y la propia estancia empezará a sentirse más grande."},
            {"t": "h2", "c": "Los cinco principios"},
            {"t": "ul", "c": [
                "Da a cada zona una única función clara; deja un rincón vacío a propósito.",
                "Maximiza la luz natural y mantén tonos de pared reflectantes.",
                "Compra muebles a la escala adecuada e invierte en una pieza protagonista.",
                "Esconde el almacenamiento en la arquitectura en lugar de añadir más muebles.",
                "Edita sin piedad: todo lo visible debe ganarse su lugar.",
            ]},
        ],
    },
    {
        "slug": "color-as-a-tool",
        "date": "2026-05-12",
        "category": "Color",
        "read_time": 6,
        "image": "blog-2.jpg",
        "title": "El color como herramienta: construir una paleta que funcione",
        "excerpt": "Olvídate de hacer coincidir el sofá con la alfombra. El color funciona como un sistema: luz, profundidad y un único gesto fuerte. Cómo construir una paleta que se sostenga.",
        "meta": "Cómo construir una paleta de color para interiores: la regla 60-30-10, la luz cálida frente a la fría, la saturación y un único acento fuerte, explicados con sencillez.",
        "blocks": [
            {"t": "p", "c": "La mayoría elige el color como quien elige un atuendo que le encanta en una foto —y luego se pregunta por qué el resultado no se sostiene. El color en una estancia funciona como un sistema, con una jerarquía, y el sistema importa más que cualquier color aislado."},
            {"t": "h2", "c": "Empieza por la luz de la estancia, no por la tendencia"},
            {"t": "p", "c": "La misma pintura se lee de forma distinta bajo luz del norte, sol de poniente y bombillas cálidas. Una estancia orientada al norte necesita tonos cálidos para sentirse viva; una bañada en sol puede sostener tonos más fríos. Antes de probar colores, observa la luz: de qué dirección viene, cómo cambia a lo largo del día y si las bombillas son cálidas o frías."},
            {"t": "h2", "c": "La estructura 60-30-10"},
            {"t": "ul", "c": [
                "60%: el tono dominante: paredes, suelo y las superficies más grandes. Mantenlo en calma.",
                "30%: el tono secundario: el sofá, el mobiliario de cocina, los muebles principales. En conversación con el primero.",
                "10%: el acento: cojines, una silla, una alfombra, arte. Aquí vive la personalidad, y debería seguir siendo accionista minoritario.",
            ]},
            {"t": "quote", "c": "Una paleta no es una colección de colores favoritos. Es un conjunto de colores que han acordado trabajar juntos."},
            {"t": "h2", "c": "Un gesto fuerte vence a cinco correctos"},
            {"t": "p", "c": "Las estancias que se perciben indecisas suelen tener varios colores haciendo cada uno un pequeño trabajo. Las que se sienten diseñadas tienen un único gesto fuerte —una pared profunda en un espacio pequeño, una isla de cocina saturada, una alfombra generosa en color, y dejan que todo lo demás caiga en silencio a su alrededor. Decide dónde quieres que aterrice la mirada, y pon allí el color más audaz, y en ningún otro sitio."},
            {"t": "h2", "c": "Una prueba práctica"},
            {"t": "p", "c": "Prueba en la pared, en la estancia real, y obsérvalo a tres horas del día. Unas tarjetas de muestra baratas y una semana de paciencia te ahorran el coste de una repintada completa. Y cuando hayas reducido a dos paletas, elige la que te resulte más serena: el color es lo más fácil de añadir más tarde y lo más difícil de restar."},
        ],
    },
    {
        "slug": "what-the-design-process-looks-like",
        "date": "2026-04-20",
        "category": "Proceso",
        "read_time": 5,
        "image": "blog-5.jpg",
        "title": "Cómo es el proceso de diseño, paso a paso",
        "excerpt": "De la primera llamada a la revelación final: un recorrido honesto y en lenguaje claro de cómo se desarrolla en realidad un proyecto residencial.",
        "meta": "Proceso de interiorismo paso a paso: descubrimiento, concepto, desarrollo, entrega. Lo que los clientes pueden esperar en cada etapa.",
        "blocks": [
            {"t": "p", "c": "Los clientes me cuentan que la parte más angustiosa de un proyecto es lo desconocido: cuánto durará, quién hace qué y a dónde va el dinero. Este es el proceso que utilizo, en lenguaje claro, para que sepas qué esperar."},
            {"t": "h2", "c": "1. Descubrimiento"},
            {"t": "p", "c": "Hablamos de cómo vives, trabajas y recibes: las rutinas, los hábitos, las cosas que hoy te molestan del espacio. Escucho la sensación que quieres que la estancia transmita. Esta etapa solo te cuesta una hora, y me dice si encajamos."},
            {"t": "h2", "c": "2. Diseño"},
            {"t": "p", "c": "Concepto, ambiente, materiales y distribución: se desarrollan juntos y se refinan hasta que el resultado parece inevitable. Verás planos, paletas y muestras de materiales, e iremos y vendremos hasta que el diseño se ajuste a la forma en que vives de verdad. Es aquí donde la visión toma forma, antes de tocar una sola pared."},
            {"t": "h2", "c": "3. Desarrollo"},
            {"t": "p", "c": "Planos técnicos, abastecimiento y coordinación con constructores y artesanos, gestionados de principio a fin. Recibes presupuestos claros y un calendario realista, y yo me ocupo de los proveedores para que tú no seas el intermediario. Las incógnitas se resuelven aquí, sobre el papel, donde resultan baratas."},
            {"t": "quote", "c": "Un buen proceso traslada los problemas al papel desde el principio, donde es barato resolverlos —no a la obra, donde resultan caros."},
            {"t": "h2", "c": "4. Entrega"},
            {"t": "p", "c": "Instalación y estilismo, hasta el último objeto. El espacio se entrega listo para vivir —no montado para una fotografía, sino dispuesto para tu semana. Es el momento en que todo encaja en silencio, y es la razón por la que existe el proceso."},
            {"t": "h2", "c": "Qué preguntarle a cualquier diseñador antes de empezar"},
            {"t": "ul", "c": [
                "¿Cómo gestionas el presupuesto —y qué ocurre si se desplaza?",
                "¿Quién coordina a los proveedores, los constructores y los plazos?",
                "¿Qué haces cuando un producto elegido se descataloga?",
                "¿Cómo nos comunicaremos, y con qué frecuencia?",
                "¿Qué cubre el honorario, y qué queda fuera de él?",
            ]},
            {"t": "p", "c": "El proceso correcto es el que te mantiene informado sin sepultarte en detalles. Siempre deberías saber en qué etapa está el proyecto, qué ocurre después y cuánto cuesta."},
        ],
    },
    {
        "slug": "seven-common-interior-design-mistakes",
        "date": "2026-03-30",
        "category": "Fundamentos",
        "read_time": 6,
        "image": "blog-6.jpg",
        "title": "Siete errores comunes en interiorismo (y cómo evitarlos)",
        "excerpt": "Los errores que envejecen una estancia en silencio no van de gusto: van de secuencia y escala. Una lista práctica antes de renovar.",
        "meta": "Errores comunes de interiorismo que conviene evitar: iluminación, escala, color, almacenamiento y secuencia. Una lista práctica para renovar.",
        "blocks": [
            {"t": "p", "c": "Después de suficientes proyectos, empiezas a ver los mismos siete errores repetidos —no en malos hogares, sino en cuidadosos y bienintencionados. Ninguno tiene que ver con el gusto. Tienen que ver con la secuencia, la escala y el lugar al que va la atención."},
            {"t": "h2", "c": "1. Planificar la decoración antes que la distribución"},
            {"t": "p", "c": "Elegir un sofá antes de decidir cómo fluye la estancia es como comprar ropa antes de saber adónde vas. Empieza por cómo se usa el espacio y cómo se mueve la gente por él; las piezas vienen después."},
            {"t": "h2", "c": "2. Comprarlo todo en una sola tienda"},
            {"t": "p", "c": "Un conjunto a juego es cómodo y olvidable. Las estancias con personalidad nacen de piezas con historias distintas: una silla vintage junto a un sofá contemporáneo, una mesa hecha a mano bajo una lámpara de gran consumo. Si todo coincide, nada importa."},
            {"t": "h2", "c": "3. Colgar el arte demasiado alto"},
            {"t": "p", "c": "El centro de un cuadro debe quedar a la altura de los ojos estando de pie —aproximadamente entre 145 y 150 cm del suelo. Sobre sofás, el borde inferior debe quedar unos 15 a 20 cm por encima del respaldo. El arte flota cuando cuelga como una placa de museo."},
            {"t": "h2", "c": "4. Pelear contra la luz en lugar de usarla"},
            {"t": "p", "c": "Elegir paredes oscuras y envolventes para una estancia orientada al norte, o una única luz de techo sin regulador, son dos formas de perder la batalla contra la condición natural del espacio. Diseña con la luz que tienes antes de añadir más."},
            {"t": "h2", "c": "5. Reducir el tamaño de todo"},
            {"t": "p", "c": "Los muebles demasiado pequeños hacen que una estancia parezca más pequeña y más vacía. Compra a la escala correcta para el espacio y deja que una pieza sea generosa."},
            {"t": "h2", "c": "6. Decorar el plano, no la estancia"},
            {"t": "p", "c": "Los planos mienten. El verdadero carácter de una estancia nace de cómo se siente en tres dimensiones: la profundidad de un pasillo, la altura de un techo, el recorrido de la luz del sol por el suelo. Dedica tanto tiempo a imaginarte dentro de la estancia como a ordenarla sobre el papel."},
            {"t": "h2", "c": "7. Añadir antes de editar"},
            {"t": "p", "c": "Cuando una estancia no se siente bien, el instinto es añadir otro objeto. Suele ser el instinto equivocado. Primero quita: una capa de objetos, una alfombra recargada, una lámpara duplicada —y observa qué estaba intentando ser la estancia. La mayoría de los espacios mejoran más por la sustracción que por la suma."},
            {"t": "quote", "c": "La vía más rápida para que una estancia se vea mejor es quitarle algo."},
        ],
    },
]
